```{r}
suppressMessages({
  library("plyr")
  library("tidyverse")
  library("ggplot2")
  library("ggrepel")
  library("UpSetR")
  library("glue")
})
```

```{r}
library(ggplot2)
options(echo = TRUE)
library(glue)
library(dplyr)
library(ggrepel)

# ALS risk genes
als_genes <- c(
  "SOD1", "C9orf72", "TARDBP", "FUS", "UBQLN2", "VCP", "OPTN", "TBK1",
  "STMN2", "UNC13A", "NEK1", "SIGMAR1", "ANG", "TUBA4A", "ALS2", "FIG4", 
  "DAO", "KIF5A", "HNRNPA1", "HNRNPA2B1", "SFPQ", "MATR3", "FMR1", "CCNF", "RBM45",
  "TARBP1","SOD2", "NEFL", "NEFH", "NEFM",
  
  # CD genes
  "CD14", "CD68", "CD163", "CD4", "CD8",
  
  # other genes we wanted to label
  "EGR1", "EGR2", "EGR3"
)

innate_immune_genes <- c(
  # Complement Pathway
  "C1QA", "C1QB", "C1QC", "C2", "C3", "C4A", "C4B", "C5", "C5AR1",
  "CFH", "CFI", "C6", "C7", "C8A", "C8B", "C8G", "C9", "MASP1", "MASP2",
  "C1", "C1R","C1S",
  
  # HLA Genes
  "HLA-A", "HLA-B", "HLA-C", "HLA-DPA1", "HLA-DPB1", "HLA-DQA1", 
  "HLA-DQB1", "HLA-DRA", "HLA-DRB1",
  
  # CCL Pathway
  "CCL2", "CCL3", "CCL3L1", "CCL4", "CCL5", "CCL7", "CCL8", "CCL11", 
  "CCL17", "CCL19", "CCL21", "CCL22", "CCL24", "CCL25", "CCL28",
  
  # Other Innate Immune Genes
  "TLR2", "TLR4", "NLRP3", "IL1B", "IL18", "TNF", "CXCL8", "CD14", 
  "S100A8", "S100A9", "NFKB1", "MYD88", "PTGS2", "ALOX5", "IFNB1", "CXCL10",
  "S100A6","CHI3L1", "CHI3L2"
)


eggen <- read.csv("/projects/p31535/thomas/1792Reference/eggen-microglia.csv")
eggen_genes <- eggen$Gene
ham <- read.csv("/projects/p31535/Anne/ham_genes.csv")
ham_genes <- ham$gene
microglia_genes <- unique(c(eggen_genes, ham_genes))

all_manual_genes <- unique(c(innate_immune_genes, als_genes, microglia_genes))


volcano <- function(results, title = NULL, label_genes = NULL, p_thresh = 0.05, fc_thresh = 0.585, 
                    num_pfc = 8) {
  
  # results <- results %>%
  #   filter(!grepl("AC0", gene_id) & gene_id != "HLA-B")
  
  # Define plot colors
  colors <- c("blue", "red", "black")
  names(colors) <- c("Downregulated", "Upregulated", "Not DE")
  
  # Rename variables 
  results$lfc <- results[["avg_log2FC"]]
  results$padj <- results[["BH"]]
  results$gene <- results[["gene"]]
  
  # Calculate PFC 
  results$neg_logBH <- -log10(results$padj)
  results$neg_logBH[results$neg_logBH == Inf] <- max(results$neg_logBH[results$neg_logBH != Inf]) + 10
  results$PFC <- results$neg_logBH*abs(results$lfc)
  
  # Define DEGs
  results$DE <- "Not DE"
  results$DE[results$padj < p_thresh & results$lfc > fc_thresh] <- "Upregulated"
  results$DE[results$padj < p_thresh & results$lfc < -fc_thresh] <- "Downregulated"


  
  # Gene labeling 
  results$label <- NA

  # If genes not specified, label top 30 by PFC, otherwise label specified genes
  if (is.null(label_genes)) {
    results <- results %>% dplyr::arrange(desc(PFC))
    # all_DE_genes_count <- dplyr::filter(results, DE != "Not DE")|>nrow()
    # degs <- results$gene[results$DE != "Not DE"][1:all_DE_genes_count]
    degs <- results$gene[results$DE != "Not DE"]
    results$label[results$gene %in% degs] <- results$gene[results$gene %in% degs]
  } else {
    results <- results %>% dplyr::arrange(desc(PFC))
    degs_PFC <- results$gene[results$DE != "Not DE"][1:num_pfc]
    all_degs <- results$gene[results$DE != "Not DE"]
    
    
    results$label[results$gene %in% degs_PFC] <- results$gene[results$gene %in% degs_PFC]
    
    
    all_label_genes <- intersect(all_degs, label_genes)
    results$label[results$gene %in% all_label_genes] <- results$gene[results$gene %in% all_label_genes]
    

  }
  # 
  # Define basic title if not specified 
  if (is.null(title)) {
    title <- paste0(sum(results$DE != "Not DE"), " DEGs")
  }
  
  # Generate plot 
  plt <- ggplot(data.frame(results), aes(x = lfc, y = neg_logBH, fill = DE, label = label)) + 
    geom_point(aes(size = PFC), alpha = 0.5, shape = 21, stroke = NA) + 
    scale_size_continuous(range = c(3, 12)) + 
    geom_label_repel(color = "black", size = 5, force = 3, min.segment.length = 0, force_pull = 0, box.padding = 1, max.overlaps = Inf,
                     fill = "white", alpha = 0.75, label.size = NA) +
    geom_vline(xintercept=c(-fc_thresh, fc_thresh), linetype = 3) + geom_hline(yintercept= -log10(p_thresh), linetype = 3) +
    scale_fill_manual(values = colors) + 
    theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(color = 'black'), aspect.ratio = 1) + 
    xlim(min(results$lfc[!is.na(results$padj)]) - 0.2, max(results$lfc[!is.na(results$padj)]) + 0.2) +
    # ylim(c(0, 50))+
    ggtitle(paste0(title)) + theme(plot.title = element_text(hjust = 0.5)) + 
    labs(x = "Log2 Fold Change", y = "-log10(Adjusted P-Value)", size = 12) +
    theme(axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14))
  
  return(plt)
}
```


# C2l enrichment plot

```{r}
p_thresh <- 0.05
fc_thresh <- log2(1.5)
regions <- c("norm_ct_Astrocytes_enriched", "norm_ct_Endothelial_enriched", "norm_ct_Ependymal.Cells_enriched", "norm_ct_Lymphocytes_enriched", 
             "norm_ct_Macrophages_enriched", "norm_ct_Meninges_enriched", "norm_ct_Microglia_enriched", "norm_ct_Neurons_enriched", "norm_ct_OPC_enriched",
             "norm_ct_Oligodendrocytes_enriched", "norm_ct_Pericytes_enriched", "norm_ct_ProliferatingMicroglia_enriched", 
             "norm_ct_Schwann_enriched")
file_suffix <- c(
  "C9orf72_vs_Control" = "C9orf72_vs._Control",
  "condition_general" = "als_vs._Control",
  "sALS_vs_Control" = "sALS_vs._Control"
)


data_root <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis"
data_dirs <- c("DE_random_effect_C2L_0116")

all_de_root <- glue("{data_root}/{data_dirs}")


for(cur_de_root in all_de_root){
  for(cur_comp in names(file_suffix)){
    for(region in regions){
      de_file <- "{cur_de_root}/{cur_comp}/data/{region}__{file_suffix[[cur_comp]]}.csv"|>glue()
      
      if(file.exists(de_file) == F){
        print(de_file)
        next
      }
      
      output_file <- "{cur_de_root}/{cur_comp}/plot/{region}__{file_suffix[[cur_comp]]}.pdf"|>glue()
      cur_df <- read.csv(de_file)
      p <- volcano(cur_df, p_thresh = p_thresh, fc_thresh = fc_thresh, title = glue("{region} all als vs. control"), label_genes = all_manual_genes, num_pfc = 12)
      pdf(output_file, width = 10, height = 10)
      print(p)
      dev.off()
    }
  }
}


```







# manual annotation plot


```{r}
p_thresh <- 0.05
fc_thresh <- log2(1.5)
regions <- c("Anterior_horns", "White_matter", "Grey_matter", "Posterior_white_matter", "Border")
file_suffix <- c(
  "C9orf72_hc" = "C9orf72_vs._Control",
  "condition_general" = "ALS_vs._Control",
  "sALS_hc" = "sALS_vs._Control"
)
data_root <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis"
data_dirs <- c("DE_random_effect_manual_1211_no_border", "DE_random_effect_manual_1211_with_border")

all_de_root <- glue("{data_root}/{data_dirs}")


for(cur_de_root in all_de_root){
  for(cur_comp in names(file_suffix)){
    for(region in regions){
      de_file <- "{cur_de_root}/{cur_comp}/data/{region}__{file_suffix[[cur_comp]]}.csv"|>glue()
      
      if(file.exists(de_file) == F){
        print(de_file)
        next
      }
      
      output_file <- "{cur_de_root}/{cur_comp}/plot/{region}__{file_suffix[[cur_comp]]}.pdf"|>glue()
      cur_df <- read.csv(de_file)
      p <- volcano(cur_df, p_thresh = p_thresh, fc_thresh = fc_thresh, title = glue("{region} all als vs. control"), label_genes = all_manual_genes, num_pfc = 12)
      pdf(output_file, width = 10, height = 10)
      print(p)
      dev.off()
    }
  }
}

```













```{r}
p_thresh <- 0.05
fc_thresh <- log2(1.5)
regions <- c("Anterior_horns", "White_matter", "Grey_matter", "Posterior_white_matter")
for(region in regions){
  de_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_no_border/condition_general/data/{region}__ALS_vs._Control.csv"|>glue()
  output_file <- glue("/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_no_border/condition_general/plot/Fig3C__all_als_vs._Control__{region}.pdf")
  cur_df <- read.csv(de_file)
  p <- volcano(cur_df, p_thresh = p_thresh, fc_thresh = fc_thresh, title = glue("{region} all als vs. control"), label_genes = all_manual_genes, num_pfc = 8)
  pdf(output_file, width = 10, height = 10)
  print(p)
  dev.off()
}







p_thresh <- 0.05
fc_thresh <- log2(1.5)
regions <- c("Anterior_horns", "White_matter", "Grey_matter", "Posterior_white_matter")
for(region in regions){
  de_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_no_border/C9orf72_hc/data/{region}__C9orf72_vs._Control.csv"|>glue()
  output_file <- glue("/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_no_border/C9orf72_hc/plot/Fig3C__C9orf72_vs._Control__{region}.pdf")
  cur_df <- read.csv(de_file)
  if(region == "Anterior_horns"){
    num_pfc <- 20
  }else{
    num_pfc <-8
  }
  p <- volcano(cur_df, p_thresh = p_thresh, fc_thresh = fc_thresh, title = glue("{region} all als vs. control"), label_genes = all_manual_genes, num_pfc = num_pfc)
  pdf(output_file, width = 10, height = 10)
  print(p)
  dev.off()
}












p_thresh <- 0.05
fc_thresh <- log2(1.5)
regions <- c("Anterior_horns", "White_matter", "Grey_matter", "Posterior_white_matter")
for(region in regions){
  de_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_no_border/sALS_hc/data/{region}__sALS_vs._Control.csv"|>glue()
  output_file <- glue("/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_no_border/sALS_hc/plot/Fig3C__sALS_vs._Control__{region}.pdf")
  cur_df <- read.csv(de_file)
  if(region == "Anterior_horns"){
    num_pfc <- 20
  }else{
    num_pfc <-8
  }
  p <- volcano(cur_df, p_thresh = p_thresh, fc_thresh = fc_thresh, title = glue("{region} all als vs. control"), label_genes = all_manual_genes, num_pfc = num_pfc)
  pdf(output_file, width = 10, height = 10)
  print(p)
  dev.off()
}









# with border

p_thresh <- 0.05
fc_thresh <- log2(1.5)
regions <- c("Anterior_horns", "White_matter", "Grey_matter", "Posterior_white_matter", "Border")
for(region in regions){
  de_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_with_border/sALS_hc/data/{region}__sALS_vs._Control.csv"|>glue()
  output_file <- glue("/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1207_with_border/sALS_hc/plot/Fig3C__sALS_vs._Control__{region}.pdf")
  cur_df <- read.csv(de_file)
  if(region == "Anterior_horns"){
    num_pfc <- 20
  }else{
    num_pfc <-8
  }
  p <- volcano(cur_df, p_thresh = p_thresh, fc_thresh = fc_thresh, title = glue("{region} all als vs. control"), label_genes = all_manual_genes, num_pfc = num_pfc)
  pdf(output_file, width = 10, height = 10)
  print(p)
  dev.off()
}

```

















```{r}
# Load results
# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/sALS_hc/data/Anterior_horns__sALS_vs._Control.csv"
# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/sALS_hc/data/White_matter__sALS_vs._Control.csv"
# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/sALS_hc/data/Grey_matter__sALS_vs._Control.csv"
# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/sALS_hc/data/Posterior_white_matter__sALS_vs._Control.csv"


# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/C9orf72_hc/data/Anterior_horns__C9orf72_vs._Control.csv"
# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/C9orf72_hc/data/White_matter__C9orf72_vs._Control.csv"
# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/C9orf72_hc/data/Grey_matter__C9orf72_vs._Control.csv"
input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_1115/C9orf72_hc/data/Posterior_white_matter__C9orf72_vs._Control.csv"


# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/crispr_clean_final/05.DEG_718_adaptive_only/degs/sALS_hc/SCT/age_sex/diagnosis_general___CD8_TEM__als_vs._healthy_control.csv"

# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/04.downstream_analysis/DE_random_effect_manual_c2l_enriched_ident2_ref/sALS_vs_Control/data/Microglia_Enriched__sALS_vs._Control.csv"






output_file <- str_replace(input_file, ".csv", ".pdf")|>str_replace("data", "plot")

title_id <- basename(input_file)|>str_remove(".csv")
# input_file <- "/projects/b1042/Gate_Lab/projects/als-project/crispr_clean_final/05.DEG_430_filter/degs/sALS_hc/SCT/age_sex/diagnosis_general___CD16_Mono__als_vs._healthy_control.csv"
# output_file <- "/projects/b1042/Gate_Lab/projects/als-project/crispr_clean_final/05.DEG_430_filter/degs/sALS_hc/SCT/age_sex/diagnosis_general___CD16_Mono__als_vs._healthy_control.pdf"
results <- read.csv(input_file)
# results[["gene_id"]] <- results[["gene"]]
results[["gene_id"]] <- results[["X"]]


# Set these variables to column names corresponding to LFC, adjusted p-value and gene name (so they can be renamed in the plot function)
lfc <- "avg_log2FC"
padj <- "BH"
gene <- "gene_id"
# Define DE thresholds
fc_thresh <- 0.585 
p_thresh <- 0.05

cur_up_genes <- dplyr::filter(results, BH < p_thresh, avg_log2FC > fc_thresh)[["gene_id"]]
print(paste0(cur_up_genes, collapse = " "))
cur_down_genes <- dplyr::filter(results, BH < p_thresh, avg_log2FC < -1 * fc_thresh)[["gene_id"]]
print(paste0(cur_down_genes, collapse = " "))


#-------------------------------------------------------------------------------
# Generate volcano plot
# Define plot function 
volcano <- function(results, title = NULL, label_genes = NULL) {
  
  results <- results %>%
    filter(!grepl("AC0", gene_id) & gene_id != "HLA-B")
  
  # Define plot colors
  colors <- c("blue", "red", "black")
  names(colors) <- c("Downregulated", "Upregulated", "Not DE")
  
  # Rename variables 
  results$lfc <- results[[lfc]]
  results$padj <- results[[padj]]
  results$gene <- results[[gene]]
  
  # Calculate PFC 
  results$neg_logBH <- -log10(results$padj)
  results$neg_logBH[results$neg_logBH == Inf] <- max(results$neg_logBH[results$neg_logBH != Inf]) + 10
  results$PFC <- results$neg_logBH*abs(results$lfc)
  
  # Define DEGs
  results$DE <- "Not DE"
  results$DE[results$padj < p_thresh & results$lfc > fc_thresh] <- "Upregulated"
  results$DE[results$padj < p_thresh & results$lfc < -fc_thresh] <- "Downregulated"
  
  # Gene labeling 
  results$label <- NA
  
  # If genes not specified, label top 30 by PFC, otherwise label specified genes
  if (is.null(label_genes)) {
    results <- results %>% dplyr::arrange(desc(PFC))
    # all_DE_genes_count <- dplyr::filter(results, DE != "Not DE")|>nrow()
    # degs <- results$gene[results$DE != "Not DE"][1:all_DE_genes_count]
    degs <- results$gene[results$DE != "Not DE"]
    results$label[results$gene %in% degs] <- results$gene[results$gene %in% degs]
  } else {
    results$label[results$gene %in% label_genes] <- results$gene[results$gene %in% label_genes]
  }
  
  # Define basic title if not specified 
  if (is.null(title)) {
    title <- paste0(sum(results$DE != "Not DE"), " DEGs")
  }
  
  # Generate plot 
  plt <- ggplot(data.frame(results), aes(x = lfc, y = neg_logBH, fill = DE, label = label)) + 
    geom_point(aes(size = PFC), alpha = 0.5, shape = 21, stroke = NA) + 
    scale_size_continuous(range = c(3, 12)) + 
    geom_label_repel(color = "black", size = 12, force = 3, min.segment.length = 0, force_pull = 0, box.padding = 1, max.overlaps = Inf,
                     fill = "white", alpha = 0.75, label.size = NA) +
    geom_vline(xintercept=c(-fc_thresh, fc_thresh), linetype = 3) + geom_hline(yintercept= -log10(p_thresh), linetype = 3) +
    scale_fill_manual(values = colors) + 
    theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(color = 'black'), aspect.ratio = 1) + 
    xlim(min(results$lfc[!is.na(results$padj)]) - 0.2, max(results$lfc[!is.na(results$padj)]) + 0.2) +
    # ylim(c(0, 50))+
    ggtitle(paste0(title)) + theme(plot.title = element_text(hjust = 0.5)) + 
    labs(x = "Log2 Fold Change", y = "-log10(Adjusted P-Value)", size = 12) +
    theme(axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14))
  
  return(plt)
}


# sALS white matter genes to label 
# neurodegeneration_genes <- c("BACE1", "MBP", "PLP1", "PSEN1", "TNFRSF21", 
#                              "UCHL1", "GPR37", "ELAVL3", "SEMA4D", "KLK6", 
#                              "MAPRE2", "MOG", "CNP")
# merged_genes <- c("ANXA2", "APOC1", "APOE", "C11orf96", "C1R", "C1S", "CD163", 
#                   "CD74", "CEBPB", "CEBPD", "CHI3L1", "CHI3L2", "GLRX", "HCLS1", 
#                   "IFI30", "LGALS3", "LYZ", "MGP", "NCF2", "NFIL3", "S100A6", 
#                   "SERPINA1", "SOD2", "TAGLN2", "TYROBP", "VIM")
# 
# merged_genes <- c(merged_genes, neurodegeneration_genes)

plt <- volcano(results, title = title_id)


pdf(output_file, width = 15, height = 12)
print(plt)
dev.off()
```

