####################################################################
# Charles Zhang
# Gate Lab
# Northwestern University
# 09/27/2023
####################################################################
# Perform differential expression on all level 2 predicted cell tyeps
####################################################################
# See README.md for additional links
options(echo = TRUE)

source("../../00.ref/config/CRISPR_clean_config.R")
seurat_output_dir <- glue("{out_dir_root}/04.seurat")
input_seurat <- glue("{seurat_output_dir}/seurat_04_05.rds")
DEG_out_dir <- glue("{out_dir_root}/05.DEG")
dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE )

method <- "SCT"
BH_thres <- 0.001
lfc_thres <- 0.585
cluster_col <- "predicted.celltype.l2"
condition_col <- "diagnosis"
skip_cov <- FALSE # since only female is present, can't use this
overwrite <- TRUE

degs_path<-glue("{DEG_out_dir}/degs/female_c9_hc/{method}")
plots_path<-glue("{DEG_out_dir}/plots/female_c9_hc/{method}")

dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(degs_path, showWarnings = FALSE, recursive = TRUE)
dir.create(plots_path, showWarnings = FALSE, recursive = TRUE)

s<-readRDS(input_seurat)
DefaultAssay(s) <- "RNA"

# subset to only c9 or female controls
s<-subset(s, subset = sex=="f")
s<-subset(s, subset= diagnosis=="healthy_control" | diagnosis=="als_c9orf72")
print(s@meta.data$diagnosis|>unique())

# remove cells without valid cell type annotation, this is relevant when labels are generated by matching barcodes
# with a reference seurat object
cells.use<-s@meta.data[which(is.na(s@meta.data[[cluster_col]])==F),]|>rownames()
s<- subset(s, cells = cells.use)

# generate all comparison permutations
clusters <- s@meta.data[[cluster_col]] |> unique() |> sort()
sample_conditions <- s@meta.data[[condition_col]] |> unique() |> sort()

comparisons <- combinations(n = length(sample_conditions), r = 2, v = sample_conditions)
comparisons <- split(comparisons, seq(nrow(comparisons)))

# add diagnnosis_celltype to metadata for identity matching during DEG analysis
s@meta.data$diagnosis_cluster <- glue('{s@meta.data[[cluster_col]]} - {s@meta.data[[condition_col]]}')
Idents(s) <- 'diagnosis_cluster'

# covariates
if(skip_cov){
  all_cov<-c("no_cov")
}else{
  all_cov<-c("no_cov", "age")
}

print("INFO: Covariates to test for:")
print(all_cov)
for (cur_cov in all_cov){
  dir.create(glue("{degs_path}/{cur_cov}"), showWarnings = TRUE)
  dir.create(glue("{plots_path}/{cur_cov}"), showWarnings = TRUE)
}


for(cluster in clusters) {
  for(comparison in comparisons) {
    title <- glue("{cluster}: {comparison[1]} vs. {comparison[2]}")|> str_replace_all("_", " ")
    filename  <-  gsub(" ", "_", glue("{cluster}__{comparison[1]}_vs._{comparison[2]}"))
    compA_cellnum<-sum(s$diagnosis_cluster==glue("{cluster} - {comparison[1]}"))
    compB_cellnum<-sum(s$diagnosis_cluster==glue("{cluster} - {comparison[2]}"))
    if(compA_cellnum<10 | compB_cellnum<10){
      print(glue("INFO: Not enough cells for {title}. Skip!"))
    }else{
      for(cur_cov_str in all_cov){
        cur_cov <-strsplit(cur_cov_str, "_")[[1]]
        if(cur_cov_str == "no_cov"){
          cur_cov <- NULL
        }
        cur_deg_out_file <- glue("{degs_path}/{cur_cov_str}/{condition_col}___{filename}.csv")
        if(file.exists(cur_deg_out_file)) {
          if(overwrite){
            degs <- find_degs(s,
                              save_path = cur_deg_out_file,
                              group_1 = glue("{cluster} - {comparison[1]}"),
                              group_2 = glue("{cluster} - {comparison[2]}"),
                              logfc.threshold = -Inf,
                              latent.vars = cur_cov,
                              mode = method
            )
          }else{
            print("INFO: Overwrite false. Only remaking volcano plot!")
            degs <- read.csv(cur_deg_out_file, row.names = 1)
          }
        }else{
          degs <- find_degs(s,
                            save_path = cur_deg_out_file,
                            group_1 = glue("{cluster} - {comparison[1]}"),
                            group_2 = glue("{cluster} - {comparison[2]}"),
                            logfc.threshold = -Inf,
                            latent.vars = cur_cov,
                            mode = method
          )
        }
        degs[["gene"]] <- rownames(degs)
        volcano_plot(degs,
                     file = glue("{plots_path}/{cur_cov_str}/{condition_col}___{filename}.pdf"),
                     title = title,
                     padj.thresh = BH_thres,
                     lfc.threshold = lfc_thres
        )
      }
    }
  }
}


# combine all pdfs
# for (cur_cov in all_cov){
#   cur_plot_dir <- glue("{plots_path}/{cur_cov}")
#   all_pdfs<-list.files(cur_plot_dir, full.names = T, pattern = "[^!]")
#   qpdf::pdf_combine(all_pdfs, output=glue("{plots_path}/{cur_cov}/!combined_female_c9_hc.pdf"))
# }
