```{r}
source("../00.ref/config/spatial_config.R")
options(echo = TRUE)
source(glue("{repo_root}/00.lib/plot/ggplot_formatting.R"))
source(glue("{repo_root}/00.lib/plot/volcano_plot.R"))

# DEG_out_dir <- glue("{out_dir_root}/04.downstream_analysis/DE_random_effect_manual_c2l_enriched_ident2_ref")
# input_data_dir <- glue("{out_dir_root}/03.seurat_process")
# s <- readRDS(glue("{input_data_dir}/data/all_samples_seurat_c2l_0809.rds"))
# 
# tdp_output_dir <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/02.spaceranger_output_v8_tdp43_0826"
# out_dir <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/08.tdp43/01.tdp43_projections"
# out_plot_dir <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/08.tdp43/02.protein"
# s <- readRDS(glue("{input_data_dir}/data/all_samples_seurat_tdp43_0829.rds"))


out_plot_dir <- "/projects/b1042/Gate_Lab/projects/als-project/spatial/08.tdp43/02.protein"

s <- readRDS(glue("{input_data_dir}/data/seurat_45.2__05.rds"))
s <- subset(s, subset = manual_3 == "Anterior_horns")
DefaultAssay(s) <- "Spatial"
s <- JoinLayers(s) 

```

```{r}
all_samples <- s$sample_combined|>unique()
all_annotation <- s$annotation_general|>unique()
all_annotation <- all_annotation[!all_annotation %in% c("Not_selected")]
all_protein <- s@assays$Protein$counts|>rownames()
sample2condition <- dplyr::select(s@meta.data, sample_combined, condition)|>unique()
s2c <- sample2condition$condition
names(s2c) <- sample2condition$sample_combined

out_df <- list()

for(cur_sample in all_samples){
  for(cur_anno in all_annotation){
    
    t <- dplyr::filter(s@meta.data, sample_combined == cur_sample, annotation_general == cur_anno)
    if(nrow(t) == 0){
      next
    }
    
    cur_s <- subset(s, subset = ((sample_combined == cur_sample) & (annotation_general == cur_anno)))
    cur_condition <- s2c[[cur_sample]]
    cur_sample_anno_summed <- cur_s@assays$Protein@counts|>
      rowMeans()
      
    cur_tibble <- tibble(
      protein = names(cur_sample_anno_summed),
      norm_expr = cur_sample_anno_summed,
      sample = cur_sample,
      annotation = cur_anno,
      condition = cur_condition
    )
    out_df[[glue("{cur_sample}__{cur_anno}")]] <- cur_tibble
  }
}

out_df <- bind_rows(out_df)
out_df[["annotation_general"]] <- sapply(out_df$annotation, function(x){
  if(x == "TDP43_distant"){
    out <- "TDP43_distant"
  }else{
    out <- "TDP43_positive"
  }
  out
})

# Create an empty list to store results
test_results <- list()
out_df$annotation_general <- factor(out_df$annotation_general, levels = c("TDP43_distant", "TDP43_positive"))

# Iterate over each unique annotation
unique_proteins <- out_df$protein|>unique()
for (protein in unique_proteins) {
  # Subset data for the current protein
  protein_data <- out_df %>% filter(protein == !!protein)
  
  # Perform the Wilcoxon rank-sum test between the two groups in condition_general
  test_result <- wilcox.test(norm_expr ~ annotation_general, data = protein_data)
  
  # Store the results
  test_results[[paste(protein, sep = "_")]] <- test_result
  
  # Extract p-value from test result
  p_value <- test_result$p.value
  if(p_value < 0.01){
    print(protein)
  }
  # Create a boxplot
  p <- ggplot(protein_data, aes(x = annotation_general, y = norm_expr, fill = annotation_general)) +
    geom_boxplot(alpha = 0.8, outlier.shape = NA) +
    geom_jitter(aes(color = annotation), position = position_jitter(width = 0.2), size = 1.5, alpha = 0.8) +
    labs(title = paste("Protein:", protein, "- p-value:", signif(p_value, digits = 3)),
         x = "Annotation",
         y = "Normalized Expression") +
    theme_Publication_blank() +
    scale_fill_manual(values = c("TDP43_distant" = "#1f77b4", "TDP43_positive" = "#ff7f0e"))+
    scale_color_manual(values = c("TDP43_distant" = "#2ca02c", "TDP43_adjacent" = "#d62728", "TDP43_positive"="yellow")) 
  
  # Save the plot
  ggsave(filename = paste0(out_plot_dir, "/", "boxplot_", protein, ".pdf"), plot = p, width = 5, height = 10)
}

```


```{r}

immune_genes <- c("CXCR5.1", "ITGAX.1", "FCGR3A.1", "CD68.1", "CD4.1", "CD274.1", "CR2.1", 
                  "CD40.1", "MS4A1.1", "CD14.1", "ITGAM.1", "PTPRC.1", "PTPRC.2", 
                  "CD27.1", 
                  "CD19.1", "HLA-DRA", "CD8A.1", "CCR7.1", "PECAM1.1", "PAX5.1", 
                  "CD3E.1", "CD163.1")

s@meta.data[["annotation_general"]] <- sapply(s@meta.data$tdp43_a2_d2, function(x){
  if(x == "Not_selected"){
    out <- "Not_selected"
  }else{
    if(x == "TDP43_distant"){
      out <- "TDP43_distant"
    }else{
      out <- "TDP43_positive"
    }
  }
  out
})

Idents(s)  <- "annotation_general"
results_sALS <- FindMarkers(s, assay = "Protein", ident.1 = "TDP43_positive", ident.2 = "TDP43_distant", test.use = "negbinom", min.pct = 0.01, logfc.threshold = -Inf, fc.slot = "counts", slot = "counts")
results_sALS$BH <- p.adjust(results_sALS$p_val, method = "BH")
results_sALS$gene <- rownames(results_sALS)
cur_title <- "TDP43_positive_vs._TDP43_distant_negbinom"
output_file <- glue("{out_plot_dir}/{cur_title}.pdf")
pdf(output_file, width = 15, height = 12)
volcano(results_sALS, title = str_replace_all(cur_title, "_", " "), label_genes = immune_genes)
dev.off()
```

```{r}
volcano <- function(results, title = NULL, label_genes = NULL, p_thresh = 0.05, fc_thresh = 0.585) {
  
  # results <- results %>%
  #   filter(!grepl("AC0", gene_id) & gene_id != "HLA-B")
  
  # Define plot colors
  colors <- c("blue", "red", "black")
  names(colors) <- c("Downregulated", "Upregulated", "Not DE")
  
  # Rename variables 
  results$lfc <- results[["avg_log2FC"]]
  results$padj <- results[["BH"]]
  results$gene <- results[["gene"]]
  
  # Calculate PFC 
  results$neg_logBH <- -log10(results$padj)
  results$neg_logBH[results$neg_logBH == Inf] <- max(results$neg_logBH[results$neg_logBH != Inf]) + 10
  results$PFC <- results$neg_logBH*abs(results$lfc)
  
  # Define DEGs
  results$DE <- "Not DE"
  results$DE[results$padj < p_thresh & results$lfc > fc_thresh] <- "Upregulated"
  results$DE[results$padj < p_thresh & results$lfc < -fc_thresh] <- "Downregulated"
  
  # Gene labeling 
  results$label <- NA

  # If genes not specified, label top 30 by PFC, otherwise label specified genes
  if (is.null(label_genes)) {
    results <- results %>% dplyr::arrange(desc(PFC))
    # all_DE_genes_count <- dplyr::filter(results, DE != "Not DE")|>nrow()
    # degs <- results$gene[results$DE != "Not DE"][1:all_DE_genes_count]
    degs <- results$gene[results$DE != "Not DE"]
    results$label[results$gene %in% degs] <- results$gene[results$gene %in% degs]
  } else {
    results$label[results$gene %in% label_genes] <- results$gene[results$gene %in% label_genes]
  }
  # 
  # Define basic title if not specified 
  if (is.null(title)) {
    title <- paste0(sum(results$DE != "Not DE"), " DEGs")
  }
  
  # Generate plot 
  plt <- ggplot(data.frame(results), aes(x = lfc, y = neg_logBH, fill = DE, label = label)) + 
    geom_point(aes(size = PFC), alpha = 0.5, shape = 21, stroke = NA) + 
    scale_size_continuous(range = c(3, 12)) + 
    geom_label_repel(color = "black", size = 12, force = 3, min.segment.length = 0, force_pull = 0, box.padding = 1, max.overlaps = Inf,
                     fill = "white", alpha = 0.75, label.size = NA) +
    geom_vline(xintercept=c(-fc_thresh, fc_thresh), linetype = 3) + geom_hline(yintercept= -log10(p_thresh), linetype = 3) +
    scale_fill_manual(values = colors) + 
    theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(color = 'black'), aspect.ratio = 1) + 
    xlim(min(results$lfc[!is.na(results$padj)]) - 0.2, max(results$lfc[!is.na(results$padj)]) + 0.2) +
    # ylim(c(0, 50))+
    ggtitle(paste0(title)) + theme(plot.title = element_text(hjust = 0.5)) + 
    labs(x = "Log2 Fold Change", y = "-log10(Adjusted P-Value)", size = 12) +
    theme(axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14))
  
  return(plt)
}
# Generate basic plot

```

