
```{r}
source("../00.ref/config/spatial_config.R")
out_dir <- glue("{out_dir_root}/03.seurat_process_final")
out_data_dir <- glue("{out_dir}/data")
out_plot_dir <- glue("{out_dir}/plot")
library(patchwork)
s <- readRDS(glue("{out_data_dir}/seurat_45.2__05.rds"))
library(ggpubr)

```


```{r fig.height=10, fig.width=10}
# only show anterior horns 
s <- subset(s, manual_3 == "Anterior_horns")

Idents(s) <- "tdp43_a2_d2"

target_gene <- "C1QC"

anterior_horns_spots <- s@meta.data|>dplyr::filter(manual_3 == "Anterior_horns")|>
  rownames()

image_show <- "GWF.20.50.10B.sl5___V52L18.332___C2"
sample_data <- subset(s, subset = sample == image_show)


t <- as.data.frame(sample_data@assays$SCT@data[target_gene,])
colnames(t) <- target_gene
sample_data <- AddMetaData(sample_data, t)

sample_data@meta.data$layeralpha <- ifelse(sample_data@meta.data$manual_3 == "Anterior_horns", 1, 0.4)
plot_data <- sample_data@meta.data |>
      mutate(
        rim_color = sample_data@meta.data$tdp43_a2_d2,
        imagecol = sample_data@images[[image_show]]@coordinates$imagecol,
        imagerow = sample_data@images[[image_show]]@coordinates$imagerow,
        feature_expression = sample_data@meta.data[[target_gene]]
      )

p <- ggplot(
  plot_data, 
  aes(
    x = imagecol,
    y = -imagerow,
    fill = feature_expression,       # numeric/continuous variable
    color = tdp43_a2_d2
    # ,             # categorical variable
    # alpha = layeralpha
  )
) +
  # Shape 21: circle that supports distinct fill and color
  geom_point(
    shape = 21,
    size  = 3,
    stroke = 0.5
  ) +
  # Use gradient for continuous fill
  scale_fill_gradient(
    low  = "white",
    high = "#FA4032"
  ) +
  # Use manual scale for categorical rim color
  scale_color_manual(
    values = c(
      "TDP43_positive" = "#188300",
      "TDP43_adjacent" = "#66d855",
      "Ring"           = "#a3ee5b",
      "TDP43_distant"  = "#d1fbd8",
      "Not_selected"   = "gray"
    )
  ) +
  # scale_alpha(range = c(0.3, 1)) +
  labs(title = target_gene) +
  theme_minimal() +
  theme(
    legend.position = "right",
    panel.grid      = element_blank(),
    axis.text       = element_blank(),
    axis.ticks      = element_blank(),
    axis.title      = element_blank(),
    aspect.ratio    = 1 
  ) +
  # Hide alpha legend if desired
  guides(alpha = "none")


pdf(glue("{out_plot_dir}/colocalization__{target_gene}.pdf"), width = 10, height = 10)
print(p)
dev.off()
  

```






# side by side 
```{r fig.height=6, fig.width=10}
Idents(s) <- "tdp43_a2_d2"

target_gene <- "C1QC"

anterior_horns_spots <- s@meta.data|>dplyr::filter(manual_3 == "Anterior_horns")|>
  rownames()

image_show <- "GWF.20.50.10B.sl5___V52L18.332___C2"
sample_data <- subset(s, subset = sample == image_show)


t <- as.data.frame(sample_data@assays$SCT@data[target_gene,])
colnames(t) <- target_gene
sample_data <- AddMetaData(sample_data, t)

sample_data@meta.data$layeralpha <- ifelse(sample_data@meta.data$manual_3 == "Anterior_horns", 1, 0.4)
plot_data <- sample_data@meta.data |>
      mutate(
        rim_color = sample_data@meta.data$tdp43_a2_d2,
        imagecol = sample_data@images[[image_show]]@coordinates$imagecol,
        imagerow = sample_data@images[[image_show]]@coordinates$imagerow,
        feature_expression = sample_data@meta.data[[target_gene]]
      )

p <- ggplot(
  plot_data, 
  aes(
    x = imagecol,
    y = -imagerow,
    color = feature_expression,       # numeric/continuous variable
    alpha = layeralpha
  )
) +
  # Shape 21: circle that supports distinct fill and color
  geom_point(
    size = sample_data@images[[image_show]]@spot.radius * 180
  ) +
  # Use gradient for continuous fill
  scale_color_gradient(
    low  = "#F6BDC0",
    high = "red"
  ) +
  # Use manual scale for categorical rim color
  # scale_alpha(range = c(0.3, 1)) +
  labs(title = target_gene) +
  theme_minimal() +
  theme(
    legend.position = "right",
    panel.grid      = element_blank(),
    axis.text       = element_blank(),
    axis.ticks      = element_blank(),
    axis.title      = element_blank(),
    aspect.ratio    = 1 
  ) +
  # Hide alpha legend if desired
  guides(alpha = "none")

# print(p)







anterior_horns_spots <- s@meta.data|>dplyr::filter(manual_3 == "Anterior_horns")|>
  rownames()

image_show <- "GWF.20.50.10B.sl5___V52L18.332___C2"
sample_data <- subset(s, subset = sample == image_show)


t <- as.data.frame(sample_data@assays$SCT@data[target_gene,])
colnames(t) <- target_gene
sample_data <- AddMetaData(sample_data, t)

sample_data@meta.data$layeralpha <- ifelse(sample_data@meta.data$manual_3 == "Anterior_horns", 1, 0.4)
plot_data <- sample_data@meta.data |>
      mutate(
        rim_color = sample_data@meta.data$tdp43_a2_d2,
        imagecol = sample_data@images[[image_show]]@coordinates$imagecol,
        imagerow = sample_data@images[[image_show]]@coordinates$imagerow,
        feature_expression = sample_data@meta.data[[target_gene]]
      )

p2 <- ggplot(
  plot_data, 
  aes(
    x = imagecol,
    y = -imagerow,
    color = tdp43_a2_d2,             # categorical variable
    alpha = layeralpha
  )
) +
  # Shape 21: circle that supports distinct fill and color
  geom_point(
    size = sample_data@images[[image_show]]@spot.radius * 180
  ) +
  # Use gradient for continuous fill
  # Use manual scale for categorical rim color
  scale_color_manual(
    values = c(
      "TDP43_positive" = "#188300",
      "TDP43_adjacent" = "#66d855",
      "Ring"           = "#a3ee5b",
      "TDP43_distant"  = "#d1fbd8",
      "Not_selected"   = "gray"
    )
  ) +
  scale_alpha(range = c(0.3, 1)) +
  labs(title = target_gene) +
  theme_minimal() +
  theme(
    legend.position = "right",
    panel.grid      = element_blank(),
    axis.text       = element_blank(),
    axis.ticks      = element_blank(),
    axis.title      = element_blank(),
    aspect.ratio    = 1 
  ) +
  # Hide alpha legend if desired
  guides(alpha = "none")

p3 <- p+p2

pdf(glue("{out_plot_dir}/colocalization__{target_gene}-double_panel.pdf"), width = 15, height = 8)
print(p3)
dev.off()
  
```



