```{r}
# source("../00.ref/config/immune_panel_config.R")
source("../00.ref/config/CRISPR_clean_config.R")
# source("../00.ref/config/immune_profiling_config.R")
library(tidyr)
seurat_output_dir <- glue("{out_dir_root}/04.seurat")
# input_seurat <- glue("{seurat_output_dir}/seurat_SCT_mapped_04_02.rds")
input_seurat <- glue("{seurat_output_dir}/seurat_04_05.rds")

s <- readRDS(input_seurat)
```

```{r fig.height=15, fig.width=15}
mt<-s@meta.data

sample_celltype_tbl <- dplyr::select(mt, orig.ident, predicted.celltype.l2, diagnosis_general)

# Calculating counts for each group
sample_celltype_stats <- sample_celltype_tbl |>
  group_by(orig.ident, predicted.celltype.l2) |>
  dplyr::summarise(count = n(), .groups = "drop")

# Calculating totals for each 'orig.ident'
totals <- sample_celltype_tbl |>
  group_by(orig.ident) |>
  dplyr::summarise(total = n(), .groups = "drop")

# Joining and calculating the percentage
sample_celltype_stats <- sample_celltype_stats |>
  left_join(totals, by = "orig.ident") |>
  mutate(percentage = (count / total) * 100) |>
  select(orig.ident, predicted.celltype.l2, percentage)


# sample_celltype_tbl <- dplyr::select(mt, orig.ident, predicted.celltype.l2, diagnosis_general)
# sample_celltype_stats <- sample_celltype_tbl |>
#   dplyr::group_by(orig.ident, predicted.celltype.l2) |>
#   dplyr::summarise(count = n()) |>
#   left_join(sample_celltype_tbl|>
#               group_by(orig.ident) |>
#               summarise(total = n())) |>
#   mutate(percentage = (count / total) * 100) |>
#   select(orig.ident, predicted.celltype.l2, percentage)

ref <- "../00.ref/meta/samples-metadata.csv"|>read.csv()
gex_idx2diagnosis_general <- ref$diagnosis_general
names(gex_idx2diagnosis_general) <- ref$gex_index
sample_celltype_stats[["diagnosis_general"]] <- sapply(sample_celltype_stats$orig.ident, 
                                                       function(x) gex_idx2diagnosis_general[[x]])

gex_idx2diagnosis <- ref$diagnosis
names(gex_idx2diagnosis) <- ref$gex_index
sample_celltype_stats[["diagnosis"]] <- sapply(sample_celltype_stats$orig.ident, 
                                                       function(x) gex_idx2diagnosis[[x]])

p <- ggplot(sample_celltype_stats, aes(x = diagnosis_general, y = percentage, fill = diagnosis_general)) +
  geom_boxplot() +
  facet_wrap(~ predicted.celltype.l2, scales = "free") +
  labs(title = "Distribution of Percentage by Cell Type and Diagnosis") +
  theme_minimal()+
  ggpubr::stat_compare_means(method = "t.test", label = "p.signif", label.y = 30)

print(p)

p <- ggplot(sample_celltype_stats, aes(x = diagnosis, y = percentage, fill = diagnosis)) +
  geom_boxplot() +
  facet_wrap(~ predicted.celltype.l2, scales = "free") +
  labs(title = "Distribution of Percentage by Cell Type and Diagnosis") +
  theme_minimal()+
  ggpubr::stat_compare_means(method = "anova", label = "p.signif", label.y = 30)

print(p)
```




```{r}
t<-dplyr::filter(sample_celltype_tbl, orig.ident == "A1")
NK_count <- dplyr::filter(t, predicted.celltype.l2=="NK")|>nrow()
NK_pct <- NK_count/nrow(t)*100 # should be 21.136
```

