####################################################################
# Charles Zhang
# Gate Lab
# Northwestern University
# 09/27/2023
####################################################################
# Perform differential expression on all level 2 predicted cell tyeps
####################################################################
# See README.md for additional links
options(echo = TRUE)

source("../../00.ref/config/immune_panel_config.R")
seurat_output_dir <- glue("{out_dir_root}/04.seurat")
input_seurat <- glue("{seurat_output_dir}/seurat_SCT_mapped_04_02.rds")
DEG_out_dir <- glue("{out_dir_root}/05.DEG")
dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE )


BH_thres <- 1e-4
lfc_thres <- 0.25
cluster_col <- "predicted.celltype.l2"
condition_col <- "diagnosis_general"
skip_cov <- FALSE

degs_path<-glue("{DEG_out_dir}/degs/{condition_col}")
plots_path<-glue("{DEG_out_dir}/plots/{condition_col}")

dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(degs_path, showWarnings = FALSE, recursive = TRUE)
dir.create(plots_path, showWarnings = FALSE,  recursive = TRUE)

s<-readRDS(input_seurat)
DefaultAssay(s) <- "RNA"

# remove cells without valid cell type annotation, this is relevant when labels are generated by matching barcodes
# with a reference seurat object
cells.use<-s@meta.data[which(is.na(s@meta.data[[cluster_col]])==F),]|>rownames()
s<- subset(s, cells = cells.use)

# generate all comparison permutations
clusters <- s@meta.data[[cluster_col]] |> unique() |> sort()
sample_conditions <- s@meta.data[[condition_col]] |> unique() |> sort()

comparisons <- combinations(n = length(sample_conditions), r = 2, v = sample_conditions)
comparisons <- split(comparisons, seq(nrow(comparisons)))

# add diagnnosis_celltype to metadata for identity matching during DEG analysis
s@meta.data$diagnosis_cluster <- glue('{s@meta.data[[cluster_col]]} - {s@meta.data[[condition_col]]}')
Idents(s) <- 'diagnosis_cluster'


# get latent vars
all_latent_vars <- colnames(s@meta.data)
latent_vars_to_use <- all_latent_vars[grep(all_latent_vars, pattern="sex|age", ignore.case = T)]

# create dir for each of the latent var
all_cov<-c(latent_vars_to_use, paste0(latent_vars_to_use, collapse="_"), "no_cov")
if(skip_cov){
  all_cov<-c("no_cov")
}

print("INFO: Covariates to test for:")
print(all_cov)
for (cur_cov in all_cov){
  dir.create(glue("{degs_path}/{cur_cov}"), showWarnings = TRUE)
  dir.create(glue("{plots_path}/{cur_cov}"), showWarnings = TRUE)
}


clusters |> mclapply(function(cluster) {
  comparisons |>lapply(function(comparison) {
    title <- glue("{cluster}: {comparison[1]} vs. {comparison[2]}")|> str_replace_all("_", " ")
    filename  <-  gsub(" ", "_", glue("{cluster}__{comparison[1]}_vs._{comparison[2]}"))
    compA_cellnum<-sum(s$diagnosis_cluster==glue("{cluster} - {comparison[1]}"))
    compB_cellnum<-sum(s$diagnosis_cluster==glue("{cluster} - {comparison[2]}"))
    if(compA_cellnum<10 | compB_cellnum<10){
      print(glue("INFO: Not enough cells for {title}. Skip!"))
    }else{

      for(cur_cov_str in all_cov){
        cur_cov <-strsplit(cur_cov_str, "_")[[1]]
        if(cur_cov_str == "no_cov"){
          cur_cov <- NULL
        }
        degs <- find_degs(s,
                          save_path = glue("{degs_path}/{cur_cov_str}/{condition_col}___{filename}.csv"),
                          group_1 = glue("{cluster} - {comparison[1]}"),
                          group_2 = glue("{cluster} - {comparison[2]}"),
                          logfc.threshold = -Inf,
                          latent.vars = cur_cov
        )
        degs[["gene"]] <- rownames(degs)
        volcano_plot(degs,
                     file = glue("{plots_path}/{cur_cov_str}/{condition_col}___{filename}.pdf"),
                     title = title,
                     padj.thresh = BH_thres,
                     lfc.threshold = lfc_thres
        )
      }
    }
  })
})

# combine all pdfs
for (cur_cov in all_cov){
  cur_plot_dir <- glue("{plots_path}/{cur_cov}")
  all_pdfs<-list.files(cur_plot_dir, full.names = T, pattern = "[^!]")
  qpdf::pdf_combine(all_pdfs, output=glue("{plots_path}/{cur_cov}/!combined_{condition_col}.pdf"))
}
