
# MAP2 masked 80 percentile ALS vs. Control MN spots 

```{r}
source("../00.ref/config/spatial_config.R")
source(glue("{repo_root}/00.lib/plot/ggplot_formatting.R"))
source(glue("{repo_root}/00.lib/plot/volcano_plot.R"))

DEG_out_dir <- glue("{out_dir_root}/04.downstream_analysis/MAP2_masked_DE")
input_data_dir <- glue("{out_dir_root}/03.seurat_process")

dir.create(DEG_out_dir, recursive = T, showWarnings = F)
dir.create(out_data_dir, recursive = T, showWarnings = F)
dir.create(out_plot_dir, recursive = T, showWarnings = F)


s <- readRDS(glue("{input_data_dir}/data/all_samples_seurat_tdp43_IF_MAP2_all_slides_1018.rds"))
DefaultAssay(s) <- "Spatial"
s <- JoinLayers(s)

comparison <- "c2l_IQR_outlier"
p_thresh <- 0.01
fc_thresh <- log2(2)
condition_col <- "condition_general"
# set idents
s@meta.data[["condition_general"]] <- sapply(s@meta.data$condition, function(x){
  if(x == "Control"){
    out <- x
  }else{
    out <- "als"
  }
})
ident.1 <- "als"
ident.2 <- "Control"

for(cur_spot_sample in s$sample|>unique()){
  cur_dist_spots <- s@meta.data|>
    dplyr::filter(c2l_IQR_outlier == "Not enriched" & sample == cur_spot_sample)|>rownames()
  cur_adj_spots <- s@meta.data|>
    dplyr::filter(c2l_IQR_outlier == "Enriched" & sample == cur_spot_sample)|>rownames()
  p <- SpatialDimPlot(s, images = cur_spot_sample, cells.highlight = list(cur_dist_spots, cur_adj_spots), cols.highlight = c("darkblue", "darkred", "grey"), ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
  print(p)
}

# keep only the enriched MAP2 spots
s <- subset(s, c2l_IQR_outlier == "Enriched")

cdr <- colMeans(GetAssayData(s, assay = "Spatial", layer = "counts") > 0)
s@meta.data$cdr <- cdr


# TODO: figure out why this is necessary?
for (name in names(s@assays$SCT@SCTModel.list)) {
  s@assays$SCT@SCTModel.list[[name]]@umi.assay <- 'Spatial'
}
s <- PrepSCTFindMarkers(object = s)

s@meta.data$cdr_centered <- as.numeric((s@meta.data$cdr - mean(s@meta.data$cdr)) / sd(s@meta.data$cdr))
s@meta.data$sample_id <- factor(s@meta.data$sample)

# Get all expression data
expressionmat_full <- GetAssayData(s, assay = "SCT", layer = 'data')
expressionmat_full <- as.matrix(expressionmat_full)



# Get avg_log2FC and percent expression for all genes
Idents(s) <- condition_col
LFC <- FoldChange(object = s, ident.1 = ident.1, ident.2 = ident.2, fc.name = "avg_log2FC", base = 2) %>% data.frame()

# Manual min.pct filtering, at least 1 group should be minimum of 10 percent
# and both groups should be at least 1 percent
genes_keep_10pct <- row.names(LFC)[LFC$pct.1 >= 0.1 | LFC$pct.2 >= 0.1]
genes_keep_1pct <- row.names(LFC)[LFC$pct.1 >= 0.01 & LFC$pct.2 >= 0.01]
genes_keep <- intersect(genes_keep_10pct, genes_keep_1pct)

# Remove contamination
if (length(grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)) != 0) {
  genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)]
}

# Filter expression matrix
expressionmat <- expressionmat_full[row.names(expressionmat_full) %in% genes_keep,]

# Cell-level and feature-level meta data for MAST
cdat <- s@meta.data
cdat$wellKey <- row.names(cdat)
fdat <- data.frame(primerid = row.names(expressionmat), row.names = row.names(expressionmat))

# Subset to conditions for comparison
cdat <- cdat[cdat[[condition_col]] %in% c(ident.1, ident.2),]
expressionmat <- expressionmat[,colnames(expressionmat) %in% row.names(cdat)]

# Create MAST object
sca <- FromMatrix(expressionmat, cdat, fdat, check_sanity = FALSE)

# Set reference level for condition
cond <- factor(colData(sca)[[condition_col]])
# TODO: figure out why setting reference as group1, which is not control, in the original script
cond <- relevel(cond, ident.2) # FindMarkers: reference level is "Group1"
colData(sca)[[condition_col]] <- cond


# MAST does not allow ebayes (empirical Bayes estimation to regularize variance) for glmer
# zlm_condition <- zlm(~ condition + sex + age_centered + cdr_centered + gDNA_centered + (1 | sample_id), sca,
#                      ebayes = FALSE, method = "glmer")
print("INFO: fitting model!")
# remove sample random variable due to insufficient variability
zlm_condition <- zlm(~ condition_general + cdr_centered, sca,
                     ebayes = FALSE, method = "glm", verbose = TRUE)
lrt_name <- paste0(condition_col, ident.1)

print("INFO: performing likelihood ratio test!")
summary_condition <- summary(zlm_condition, doLRT = lrt_name) # FindMarkers: doLRT = "conditionGroup2"

# From FindMarkers code
summary_data <- summary_condition$datatable %>% data.frame()
p_val <- summary_data[summary_data[, "component"] == "H", 4]
genes.return <- summary_data[summary_data[, "component"] == "H", 1]

# Compile results
results <- data.frame(p_val = p_val, gene = genes.return, row.names = genes.return)
results$BH <- p.adjust(results$p_val, method = "BH")

LFC_use <- LFC[match(results$gene, row.names(LFC)),]
results$avg_log2FC <- LFC_use$avg_log2FC

results$DE <- "Not DE"
results$DE[results$avg_log2FC > fc_thresh & results$BH < p_thresh] <- "Upregulated"
results$DE[results$avg_log2FC < -fc_thresh & results$BH < p_thresh] <- "Downregulated"

# For volcano plot labels
results$DE_gene <- NA
results$DE_gene[results$DE != "Not DE"] <- results$gene[results$DE != "Not DE"]

out_file <- glue("{out_data_dir}/{comparison}__{ident.1}_vs._{ident.2}.csv")
write.csv(results, out_file, quote = F)
print(glue("INFO: saved output to {out_file}!"))

output_file <- glue("{out_plot_dir}/{comparison}.pdf")
# all_DEs <- dplyr::filter(results, DE != "Not DE", avg_log2FC >1 )[["gene"]]

cur_title <- "Anterior Horns MAP mask MN enriched IQR outliers"
pdf(output_file, width = 15, height = 12)
volcano(results, title = str_replace_all(cur_title, "_", " "), p_thresh = 1e-2, fc_thresh = 1)
dev.off()
```








```{r}
volcano <- function(results, title = NULL, label_genes = NULL, p_thresh = 0.05, fc_thresh = 0.585) {
  
  # results <- results %>%
  #   filter(!grepl("AC0", gene_id) & gene_id != "HLA-B")
  
  # Define plot colors
  colors <- c("blue", "red", "black")
  names(colors) <- c("Downregulated", "Upregulated", "Not DE")
  
  # Rename variables 
  results$lfc <- results[["avg_log2FC"]]
  results$padj <- results[["BH"]]
  results$gene <- results[["gene"]]
  
  # Calculate PFC 
  results$neg_logBH <- -log10(results$padj)
  results$neg_logBH[results$neg_logBH == Inf] <- max(results$neg_logBH[results$neg_logBH != Inf]) + 10
  results$PFC <- results$neg_logBH*abs(results$lfc)
  
  # Define DEGs
  results$DE <- "Not DE"
  results$DE[results$padj < p_thresh & results$lfc > fc_thresh] <- "Upregulated"
  results$DE[results$padj < p_thresh & results$lfc < -fc_thresh] <- "Downregulated"
  
  # Gene labeling 
  results$label <- NA

  # If genes not specified, label top 30 by PFC, otherwise label specified genes
  if (is.null(label_genes)) {
    results <- results %>% dplyr::arrange(desc(PFC))
    # all_DE_genes_count <- dplyr::filter(results, DE != "Not DE")|>nrow()
    # degs <- results$gene[results$DE != "Not DE"][1:all_DE_genes_count]
    degs <- results$gene[results$DE != "Not DE"]
    results$label[results$gene %in% degs] <- results$gene[results$gene %in% degs]
  } else {
    results$label[results$gene %in% label_genes] <- results$gene[results$gene %in% label_genes]
  }
  # 
  # Define basic title if not specified 
  if (is.null(title)) {
    title <- paste0(sum(results$DE != "Not DE"), " DEGs")
  }
  
  # Generate plot 
  plt <- ggplot(data.frame(results), aes(x = lfc, y = neg_logBH, fill = DE, label = label)) + 
    geom_point(aes(size = PFC), alpha = 0.5, shape = 21, stroke = NA) + 
    scale_size_continuous(range = c(3, 12)) + 
    geom_label_repel(color = "black", size = 12, force = 3, min.segment.length = 0, force_pull = 0, box.padding = 1, max.overlaps = Inf,
                     fill = "white", alpha = 0.75, label.size = NA) +
    geom_vline(xintercept=c(-fc_thresh, fc_thresh), linetype = 3) + geom_hline(yintercept= -log10(p_thresh), linetype = 3) +
    scale_fill_manual(values = colors) + 
    theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(color = 'black'), aspect.ratio = 1) + 
    xlim(min(results$lfc[!is.na(results$padj)]) - 0.2, max(results$lfc[!is.na(results$padj)]) + 0.2) +
    # ylim(c(0, 50))+
    ggtitle(paste0(title)) + theme(plot.title = element_text(hjust = 0.5)) + 
    labs(x = "Log2 Fold Change", y = "-log10(Adjusted P-Value)", size = 12) +
    theme(axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14))
  
  return(plt)
}
```


