```{r}
source("../00.ref/config/spatial_config.R")
source(glue("{repo_root}/00.lib/plot/ggplot_formatting.R"))
source(glue("{repo_root}/00.lib/plot/volcano_plot.R"))

DEG_out_dir <- glue("{out_dir_root}/04.downstream_analysis/MN_DE")
input_data_dir <- glue("{out_dir_root}/03.seurat_process_final")

out_data_dir <- glue("{DEG_out_dir}/data")
out_plot_dir <- glue("{DEG_out_dir}/plot")


dir.create(DEG_out_dir, recursive = T, showWarnings = F)
dir.create(out_data_dir, recursive = T, showWarnings = F)
dir.create(out_plot_dir, recursive = T, showWarnings = F)



# ALS risk genes
als_genes <- c(
  "SOD1", "C9orf72", "TARDBP", "FUS", "UBQLN2", "VCP", "OPTN", "TBK1",
  "STMN2", "UNC13A", "NEK1", "SIGMAR1", "ANG", "TUBA4A", "ALS2", "FIG4", 
  "DAO", "KIF5A", "HNRNPA1", "HNRNPA2B1", "SFPQ", "MATR3", "FMR1", "CCNF", "RBM45",
  "TARBP1","SOD2", "NEFL", "NEFH", "NEFM",
  
  # CD genes
  "CD14", "CD68", "CD163", "CD4", "CD8",
  
  # other genes we wanted to label
  "EGR1", "EGR2", "EGR3"
)

innate_immune_genes <- c(
  # Complement Pathway
  "C1QA", "C1QB", "C1QC", "C2", "C3", "C4A", "C4B", "C5", "C5AR1",
  "CFH", "CFI", "C6", "C7", "C8A", "C8B", "C8G", "C9", "MASP1", "MASP2",
  "C1", "C1R","C1S",
  
  # HLA Genes
  "HLA-A", "HLA-B", "HLA-C", "HLA-DPA1", "HLA-DPB1", "HLA-DQA1", 
  "HLA-DQB1", "HLA-DRA", "HLA-DRB1",
  
  # CCL Pathway
  "CCL2", "CCL3", "CCL3L1", "CCL4", "CCL5", "CCL7", "CCL8", "CCL11", 
  "CCL17", "CCL19", "CCL21", "CCL22", "CCL24", "CCL25", "CCL28",
  
  # Other Innate Immune Genes
  "TLR2", "TLR4", "NLRP3", "IL1B", "IL18", "TNF", "CXCL8", "CD14", 
  "S100A8", "S100A9", "NFKB1", "MYD88", "PTGS2", "ALOX5", "IFNB1", "CXCL10",
  "S100A6","CHI3L1", "CHI3L2"
)


eggen <- read.csv("/projects/p31535/thomas/1792Reference/eggen-microglia.csv")
eggen_genes <- eggen$Gene
ham <- read.csv("/projects/p31535/Anne/ham_genes.csv")
ham_genes <- ham$gene
microglia_genes <- unique(c(eggen_genes, ham_genes))

all_manual_genes <- unique(c(innate_immune_genes, als_genes, microglia_genes))


volcano <- function(results, title = NULL, label_genes = NULL, p_thresh = 0.05, fc_thresh = 0.585, 
                    num_pfc = 8) {
  
  # results <- results %>%
  #   filter(!grepl("AC0", gene_id) & gene_id != "HLA-B")
  
  # Define plot colors
  colors <- c("blue", "red", "black")
  names(colors) <- c("Downregulated", "Upregulated", "Not DE")
  
  # Rename variables 
  results$lfc <- results[["avg_log2FC"]]
  results$padj <- results[["BH"]]
  results$gene <- results[["gene"]]
  
  # Calculate PFC 
  results$neg_logBH <- -log10(results$padj)
  results$neg_logBH[results$neg_logBH == Inf] <- max(results$neg_logBH[results$neg_logBH != Inf]) + 10
  results$PFC <- results$neg_logBH*abs(results$lfc)
  
  # Define DEGs
  results$DE <- "Not DE"
  results$DE[results$padj < p_thresh & results$lfc > fc_thresh] <- "Upregulated"
  results$DE[results$padj < p_thresh & results$lfc < -fc_thresh] <- "Downregulated"


  
  # Gene labeling 
  results$label <- NA

  # If genes not specified, label top 30 by PFC, otherwise label specified genes
  if (is.null(label_genes)) {
    results <- results %>% dplyr::arrange(desc(PFC))
    # all_DE_genes_count <- dplyr::filter(results, DE != "Not DE")|>nrow()
    # degs <- results$gene[results$DE != "Not DE"][1:all_DE_genes_count]
    degs <- results$gene[results$DE != "Not DE"]
    results$label[results$gene %in% degs] <- results$gene[results$gene %in% degs]
  } else {
    results <- results %>% dplyr::arrange(desc(PFC))
    degs_PFC <- results$gene[results$DE != "Not DE"][1:num_pfc]
    all_degs <- results$gene[results$DE != "Not DE"]
    
    
    results$label[results$gene %in% degs_PFC] <- results$gene[results$gene %in% degs_PFC]
    
    
    all_label_genes <- intersect(all_degs, label_genes)
    results$label[results$gene %in% all_label_genes] <- results$gene[results$gene %in% all_label_genes]
    

  }
  # 
  # Define basic title if not specified 
  if (is.null(title)) {
    title <- paste0(sum(results$DE != "Not DE"), " DEGs")
  }
  
  # Generate plot 
  plt <- ggplot(data.frame(results), aes(x = lfc, y = neg_logBH, fill = DE, label = label)) + 
    geom_point(aes(size = PFC), alpha = 0.5, shape = 21, stroke = NA) + 
    scale_size_continuous(range = c(3, 12)) + 
    geom_label_repel(color = "black", size = 5, force = 3, min.segment.length = 0, force_pull = 0, box.padding = 1, max.overlaps = Inf,
                     fill = "white", alpha = 0.75, label.size = NA) +
    geom_vline(xintercept=c(-fc_thresh, fc_thresh), linetype = 3) + geom_hline(yintercept= -log10(p_thresh), linetype = 3) +
    scale_fill_manual(values = colors) + 
    theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(color = 'black'), aspect.ratio = 1) + 
    xlim(min(results$lfc[!is.na(results$padj)]) - 0.2, max(results$lfc[!is.na(results$padj)]) + 0.2) +
    # ylim(c(0, 50))+
    ggtitle(paste0(title)) + theme(plot.title = element_text(hjust = 0.5)) + 
    labs(x = "Log2 Fold Change", y = "-log10(Adjusted P-Value)", size = 12) +
    theme(axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14))
  
  return(plt)
}
```


# all ALS vs. All controls MN distance map group 1 only 

```{r}
s <- readRDS(glue("{input_data_dir}/data/seurat_45.2__05.rds"))
s <- subset(s, subset = manual_3 == "Anterior_horns")
DefaultAssay(s) <- "Spatial"
s <- JoinLayers(s)


comparison <- "MN_group1_condition_general"
comparison_meta_col <- "MN_dist_group"
# only AH
p_thresh <- 0.05
fc_thresh <- log2(1.5)
condition_col <- "condition_general"

ident.1 <- "als"
ident.2 <- "Control"


# keep only the enriched MAP2 spots
t <- dplyr::filter(s@meta.data, manual_3 == "Anterior_horns")|>
  dplyr::select(sample_combined, MN_dist_group)|>
  table()|>
  as.data.frame()|>
  dplyr::filter(MN_dist_group == "group 1", Freq > 10)
samples_to_keep <- t[["sample_combined"]]

# Combine counts across samples
DefaultAssay(s) <- "SCT"
s <- subset(s, subset = sample_combined %in% samples_to_keep)
s <- subset(s, subset = ((manual_3 == cur_ct) & (MN_dist_group == "group 1")))


Idents(s) <- comparison_meta_col
for(cur_spot_sample in s$sample|>unique()){
  print(cur_spot_sample)
    # p <- SpatialDimPlot(s, images = cur_spot_sample, cells.highlight = list(all_dist_spots, all_adj_spots, all_tdp43_spots, ring_spots), cols.highlight = c("darkblue", "darkred", "yellow", "green", "grey"), ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
    p <- SpatialDimPlot(s, images = cur_spot_sample, ncol = 1, pt.size.factor = 2, image.alpha = 0.75)
  print(p)
}


cdr <- colMeans(GetAssayData(s, assay = "Spatial", layer = "counts") > 0)
s@meta.data$cdr <- cdr


# TODO: figure out why this is necessary?
for (name in names(s@assays$SCT@SCTModel.list)) {
  s@assays$SCT@SCTModel.list[[name]]@umi.assay <- 'Spatial'
}
s <- PrepSCTFindMarkers(object = s)

s@meta.data$cdr_centered <- as.numeric((s@meta.data$cdr - mean(s@meta.data$cdr)) / sd(s@meta.data$cdr))
s@meta.data$sample_id <- factor(s@meta.data$sample)

# Get all expression data
expressionmat_full <- GetAssayData(s, assay = "SCT", layer = 'data')
expressionmat_full <- as.matrix(expressionmat_full)



# Get avg_log2FC and percent expression for all genes
Idents(s) <- condition_col
LFC <- FoldChange(object = s, ident.1 = ident.1, ident.2 = ident.2, fc.name = "avg_log2FC", base = 2, assay = "SCT") %>% data.frame()

# Manual min.pct filtering, at least 1 group should be minimum of 10 percent
# and both groups should be at least 1 percent
genes_keep_10pct <- row.names(LFC)[LFC$pct.1 >= 0.1 | LFC$pct.2 >= 0.1]
genes_keep_1pct <- row.names(LFC)[LFC$pct.1 >= 0.01 & LFC$pct.2 >= 0.01]
genes_keep <- intersect(genes_keep_10pct, genes_keep_1pct)

# Remove contamination
if (length(grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)) != 0) {
  genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)]
}

# Filter expression matrix
expressionmat <- expressionmat_full[row.names(expressionmat_full) %in% genes_keep,]

# Cell-level and feature-level meta data for MAST
cdat <- s@meta.data
cdat$wellKey <- row.names(cdat)
fdat <- data.frame(primerid = row.names(expressionmat), row.names = row.names(expressionmat))

# Subset to conditions for comparison
cdat <- cdat[cdat[[condition_col]] %in% c(ident.1, ident.2),]
expressionmat <- expressionmat[,colnames(expressionmat) %in% row.names(cdat)]

# Create MAST object
sca <- FromMatrix(expressionmat, cdat, fdat, check_sanity = FALSE)

# Set reference level for condition
cond <- factor(colData(sca)[[condition_col]])
# TODO: figure out why setting reference as group1, which is not control, in the original script
cond <- relevel(cond, ident.2) # FindMarkers: reference level is "Group1"
colData(sca)[[condition_col]] <- cond


# MAST does not allow ebayes (empirical Bayes estimation to regularize variance) for glmer
# zlm_condition <- zlm(~ condition + sex + age_centered + cdr_centered + gDNA_centered + (1 | sample_id), sca,
#                      ebayes = FALSE, method = "glmer")
print("INFO: fitting model!")
# remove sample random variable due to insufficient variability
zlm_condition <- zlm(~ condition_general + cdr_centered, sca,
                     ebayes = FALSE, method = "glm", verbose = TRUE)
lrt_name <- paste0(condition_col, ident.1)

print("INFO: performing likelihood ratio test!")
summary_condition <- summary(zlm_condition, doLRT = lrt_name) # FindMarkers: doLRT = "conditionGroup2"

# From FindMarkers code
summary_data <- summary_condition$datatable %>% data.frame()
p_val <- summary_data[summary_data[, "component"] == "H", 4]
genes.return <- summary_data[summary_data[, "component"] == "H", 1]

# Compile results
results <- data.frame(p_val = p_val, gene = genes.return, row.names = genes.return)
results$BH <- p.adjust(results$p_val, method = "BH")

LFC_use <- LFC[match(results$gene, row.names(LFC)),]
results$avg_log2FC <- LFC_use$avg_log2FC

results$DE <- "Not DE"
results$DE[results$avg_log2FC > fc_thresh & results$BH < p_thresh] <- "Upregulated"
results$DE[results$avg_log2FC < -fc_thresh & results$BH < p_thresh] <- "Downregulated"

# For volcano plot labels
results$DE_gene <- NA
results$DE_gene[results$DE != "Not DE"] <- results$gene[results$DE != "Not DE"]

out_file <- glue("{out_data_dir}/{comparison}__{ident.1}_vs._{ident.2}.csv")
write.csv(results, out_file, quote = F)
print(glue("INFO: saved output to {out_file}!"))

output_file <- glue("{out_plot_dir}/{comparison}.pdf")
all_DEs <- dplyr::filter(results, DE != "Not DE" )[["gene"]]

extreme_DEs <- dplyr::filter(results, DE != "Not DE",  abs(avg_log2FC) > 2 & BH < 1e-50)[["gene"]]


cur_title <- "MN tracing group1 DE all ALS vs. Control"
pdf(output_file, width = 10, height = 10)
volcano(results, title = str_replace_all(cur_title, "_", " "), p_thresh = p_thresh, fc_thresh = fc_thresh, label_genes = c(innate_immune_genes, als_genes), num_pfc = 20)
dev.off()
```

# all ALS vs. All controls 

```{r}
s <- readRDS(glue("{input_data_dir}/data/all_samples_seurat_tdp43_IF_all_slides_1025.rds"))
DefaultAssay(s) <- "Spatial"
s <- JoinLayers(s)


comparison <- "MN_condition_general"
comparison_meta_col <- "MN_adjacent"
p_thresh <- 0.01
fc_thresh <- log2(2)
condition_col <- "condition_general"

ident.1 <- "als"
ident.2 <- "Control"


# keep only the enriched MAP2 spots
s <- subset(s, cells = rownames(s@meta.data[s@meta.data[[comparison_meta_col]] == "MN_adjacent", ]))
Idents(s) <- comparison_meta_col
for(cur_spot_sample in s$sample|>unique()){
  print(cur_spot_sample)
    # p <- SpatialDimPlot(s, images = cur_spot_sample, cells.highlight = list(all_dist_spots, all_adj_spots, all_tdp43_spots, ring_spots), cols.highlight = c("darkblue", "darkred", "yellow", "green", "grey"), ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
    p <- SpatialDimPlot(s, images = cur_spot_sample, ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
  print(p)
}


cdr <- colMeans(GetAssayData(s, assay = "Spatial", layer = "counts") > 0)
s@meta.data$cdr <- cdr


# TODO: figure out why this is necessary?
for (name in names(s@assays$SCT@SCTModel.list)) {
  s@assays$SCT@SCTModel.list[[name]]@umi.assay <- 'Spatial'
}
s <- PrepSCTFindMarkers(object = s)

s@meta.data$cdr_centered <- as.numeric((s@meta.data$cdr - mean(s@meta.data$cdr)) / sd(s@meta.data$cdr))
s@meta.data$sample_id <- factor(s@meta.data$sample)

# Get all expression data
expressionmat_full <- GetAssayData(s, assay = "SCT", layer = 'data')
expressionmat_full <- as.matrix(expressionmat_full)



# Get avg_log2FC and percent expression for all genes
Idents(s) <- condition_col
LFC <- FoldChange(object = s, ident.1 = ident.1, ident.2 = ident.2, fc.name = "avg_log2FC", base = 2, assay = "SCT") %>% data.frame()

# Manual min.pct filtering, at least 1 group should be minimum of 10 percent
# and both groups should be at least 1 percent
genes_keep_10pct <- row.names(LFC)[LFC$pct.1 >= 0.1 | LFC$pct.2 >= 0.1]
genes_keep_1pct <- row.names(LFC)[LFC$pct.1 >= 0.01 & LFC$pct.2 >= 0.01]
genes_keep <- intersect(genes_keep_10pct, genes_keep_1pct)

# Remove contamination
if (length(grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)) != 0) {
  genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)]
}

# Filter expression matrix
expressionmat <- expressionmat_full[row.names(expressionmat_full) %in% genes_keep,]

# Cell-level and feature-level meta data for MAST
cdat <- s@meta.data
cdat$wellKey <- row.names(cdat)
fdat <- data.frame(primerid = row.names(expressionmat), row.names = row.names(expressionmat))

# Subset to conditions for comparison
cdat <- cdat[cdat[[condition_col]] %in% c(ident.1, ident.2),]
expressionmat <- expressionmat[,colnames(expressionmat) %in% row.names(cdat)]

# Create MAST object
sca <- FromMatrix(expressionmat, cdat, fdat, check_sanity = FALSE)

# Set reference level for condition
cond <- factor(colData(sca)[[condition_col]])
# TODO: figure out why setting reference as group1, which is not control, in the original script
cond <- relevel(cond, ident.2) # FindMarkers: reference level is "Group1"
colData(sca)[[condition_col]] <- cond


# MAST does not allow ebayes (empirical Bayes estimation to regularize variance) for glmer
# zlm_condition <- zlm(~ condition + sex + age_centered + cdr_centered + gDNA_centered + (1 | sample_id), sca,
#                      ebayes = FALSE, method = "glmer")
print("INFO: fitting model!")
# remove sample random variable due to insufficient variability
zlm_condition <- zlm(~ condition_general + cdr_centered, sca,
                     ebayes = FALSE, method = "glm", verbose = TRUE)
lrt_name <- paste0(condition_col, ident.1)

print("INFO: performing likelihood ratio test!")
summary_condition <- summary(zlm_condition, doLRT = lrt_name) # FindMarkers: doLRT = "conditionGroup2"

# From FindMarkers code
summary_data <- summary_condition$datatable %>% data.frame()
p_val <- summary_data[summary_data[, "component"] == "H", 4]
genes.return <- summary_data[summary_data[, "component"] == "H", 1]

# Compile results
results <- data.frame(p_val = p_val, gene = genes.return, row.names = genes.return)
results$BH <- p.adjust(results$p_val, method = "BH")

LFC_use <- LFC[match(results$gene, row.names(LFC)),]
results$avg_log2FC <- LFC_use$avg_log2FC

results$DE <- "Not DE"
results$DE[results$avg_log2FC > fc_thresh & results$BH < p_thresh] <- "Upregulated"
results$DE[results$avg_log2FC < -fc_thresh & results$BH < p_thresh] <- "Downregulated"

# For volcano plot labels
results$DE_gene <- NA
results$DE_gene[results$DE != "Not DE"] <- results$gene[results$DE != "Not DE"]

out_file <- glue("{out_data_dir}/{comparison}__{ident.1}_vs._{ident.2}.csv")
write.csv(results, out_file, quote = F)
print(glue("INFO: saved output to {out_file}!"))

output_file <- glue("{out_plot_dir}/{comparison}.pdf")
all_DEs <- dplyr::filter(results, DE != "Not DE" )[["gene"]]

extreme_DEs <- dplyr::filter(results, DE != "Not DE",  abs(avg_log2FC) > 2 & BH < 1e-50)[["gene"]]

genes_related_to_neurodegeneration_or_immune_response_v2 <- c(
  "AIF1", "CD44", "GPNMB", "SOD2", "TREM2", "TYROBP", "VIM", # Neurodegeneration
  "NEFH", "NEFL", "NEFM", # Neurofilaments, related to neurodegeneration
  "ABCA1", "AIF1", "B2M", "C1QA", "C1QB", "C1QC", "C1R", "C1S", "C3", "CD14", 
  "CD163", "CD74", "CEBPD", "CHI3L1", "CSF1R", "CYBB", "FCGR3A", "FPR1", 
  "GPNMB", "HAMP", "IFI30", "LAPTM5", "PLSCR1", "S100A9", "SERPINA1", 
  "TREM2", "TYROBP", "STMN2", "APOC1", "TMEM176B" # Immune response
)

genes_related_to_neurodegeneration_or_immune_response_v2 <- c(genes_related_to_neurodegeneration_or_immune_response_v2, extreme_DEs)
cur_title <- "MN tracing adjacent DE all ALS vs. Control"
pdf(output_file, width = 15, height = 12)
volcano(results, title = str_replace_all(cur_title, "_", " "), p_thresh = , fc_thresh = 1, label_genes = genes_related_to_neurodegeneration_or_immune_response_v2)
dev.off()
```











# sporadic ALS vs. All controls 
```{r}
s <- readRDS(glue("{input_data_dir}/data/all_samples_seurat_tdp43_IF_all_slides_1025.rds"))
DefaultAssay(s) <- "Spatial"
s <- JoinLayers(s)

comparison <- "MN_sALS"
comparison_meta_col <- "MN_adjacent"
p_thresh <- 0.001
fc_thresh <- log2(1.5)
condition_col <- "condition"

ident.1 <- "sALS"
ident.2 <- "Control"


# keep only the enriched MAP2 spots
s <- subset(s, cells = rownames(s@meta.data[s@meta.data[[comparison_meta_col]] == "MN_adjacent", ]))

# keep only sALS and control 
s <- subset(s, subset = (condition == "sALS") | (condition == "Control"))


# check on sample condition 
print(s$condition|>unique())
# should be around 8000
print(dim(s))

Idents(s) <- comparison_meta_col
for(cur_spot_sample in s$sample|>unique()){
  print(cur_spot_sample)
    # p <- SpatialDimPlot(s, images = cur_spot_sample, cells.highlight = list(all_dist_spots, all_adj_spots, all_tdp43_spots, ring_spots), cols.highlight = c("darkblue", "darkred", "yellow", "green", "grey"), ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
    p <- SpatialDimPlot(s, images = cur_spot_sample, ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
  print(p)
}


cdr <- colMeans(GetAssayData(s, assay = "Spatial", layer = "counts") > 0)
s@meta.data$cdr <- cdr


# TODO: figure out why this is necessary?
for (name in names(s@assays$SCT@SCTModel.list)) {
  s@assays$SCT@SCTModel.list[[name]]@umi.assay <- 'Spatial'
}
s <- PrepSCTFindMarkers(object = s)

s@meta.data$cdr_centered <- as.numeric((s@meta.data$cdr - mean(s@meta.data$cdr)) / sd(s@meta.data$cdr))
s@meta.data$sample_id <- factor(s@meta.data$sample)

# Get all expression data
expressionmat_full <- GetAssayData(s, assay = "SCT", layer = 'data')
expressionmat_full <- as.matrix(expressionmat_full)



# Get avg_log2FC and percent expression for all genes
Idents(s) <- condition_col
LFC <- FoldChange(object = s, ident.1 = ident.1, ident.2 = ident.2, fc.name = "avg_log2FC", base = 2, assay = "SCT") %>% data.frame()

# Manual min.pct filtering, at least 1 group should be minimum of 10 percent
# and both groups should be at least 1 percent
genes_keep_10pct <- row.names(LFC)[LFC$pct.1 >= 0.1 | LFC$pct.2 >= 0.1]
genes_keep_1pct <- row.names(LFC)[LFC$pct.1 >= 0.01 & LFC$pct.2 >= 0.01]
genes_keep <- intersect(genes_keep_10pct, genes_keep_1pct)

# Remove contamination
if (length(grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)) != 0) {
  genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)]
}

# Filter expression matrix
expressionmat <- expressionmat_full[row.names(expressionmat_full) %in% genes_keep,]

# Cell-level and feature-level meta data for MAST
cdat <- s@meta.data
cdat$wellKey <- row.names(cdat)
fdat <- data.frame(primerid = row.names(expressionmat), row.names = row.names(expressionmat))

# Subset to conditions for comparison
cdat <- cdat[cdat[[condition_col]] %in% c(ident.1, ident.2),]
expressionmat <- expressionmat[,colnames(expressionmat) %in% row.names(cdat)]

# Create MAST object
sca <- FromMatrix(expressionmat, cdat, fdat, check_sanity = FALSE)

# Set reference level for condition
cond <- factor(colData(sca)[[condition_col]])
# TODO: figure out why setting reference as group1, which is not control, in the original script
cond <- relevel(cond, ident.2) # FindMarkers: reference level is "Group1"
colData(sca)[[condition_col]] <- cond


# MAST does not allow ebayes (empirical Bayes estimation to regularize variance) for glmer
# zlm_condition <- zlm(~ condition + sex + age_centered + cdr_centered + gDNA_centered + (1 | sample_id), sca,
#                      ebayes = FALSE, method = "glmer")
print("INFO: fitting model!")
# remove sample random variable due to insufficient variability
zlm_condition <- zlm(~ condition + cdr_centered, sca,
                     ebayes = FALSE, method = "glm", verbose = TRUE)
lrt_name <- paste0(condition_col, ident.1)

print("INFO: performing likelihood ratio test!")
summary_condition <- summary(zlm_condition, doLRT = lrt_name) # FindMarkers: doLRT = "conditionGroup2"

# From FindMarkers code
summary_data <- summary_condition$datatable %>% data.frame()
p_val <- summary_data[summary_data[, "component"] == "H", 4]
genes.return <- summary_data[summary_data[, "component"] == "H", 1]

# Compile results
results <- data.frame(p_val = p_val, gene = genes.return, row.names = genes.return)
results$BH <- p.adjust(results$p_val, method = "BH")

LFC_use <- LFC[match(results$gene, row.names(LFC)),]
results$avg_log2FC <- LFC_use$avg_log2FC

results$DE <- "Not DE"
results$DE[results$avg_log2FC > fc_thresh & results$BH < p_thresh] <- "Upregulated"
results$DE[results$avg_log2FC < -fc_thresh & results$BH < p_thresh] <- "Downregulated"

# For volcano plot labels
results$DE_gene <- NA
results$DE_gene[results$DE != "Not DE"] <- results$gene[results$DE != "Not DE"]

out_file <- glue("{out_data_dir}/{comparison}__{ident.1}_vs._{ident.2}.csv")
write.csv(results, out_file, quote = F)
print(glue("INFO: saved output to {out_file}!"))

output_file <- glue("{out_plot_dir}/{comparison}.pdf")
all_DEs <- dplyr::filter(results, DE != "Not DE" )[["gene"]]

extreme_DEs <- dplyr::filter(results, DE != "Not DE",  abs(avg_log2FC) > 1 & BH < 1e-50)[["gene"]]
# 
genes_neuro_immune_cryptic_splicing <- c(
  "APOE", "CD44", "CHI3L1", "C1QC", "C3", "CEBPD", "CTSB", "CTSZ", 
  "GFAP", "IFI27", "IFI6", "KIF5A", "MAOB", "NEFH", "NEFL", "NEFM", 
  "NUPR1", "S100A6", "S100A9", "SOD2", "STMN2", "UCHL1", "VIM"
)

genes_neuro_immune_cryptic_splicing <- c(genes_neuro_immune_cryptic_splicing, extreme_DEs)
cur_title <- "MN tracing adjacent DE sALS vs. Control"
pdf(output_file, width = 15, height = 12)
volcano(results, title = str_replace_all(cur_title, "_", " "), p_thresh = 1e-3, fc_thresh = fc_thresh, label_genes = genes_neuro_immune_cryptic_splicing)
dev.off()
```














# sporadic ALS vs. All controls 
```{r}
s <- readRDS(glue("{input_data_dir}/data/all_samples_seurat_tdp43_IF_all_slides_1025.rds"))
DefaultAssay(s) <- "Spatial"
s <- JoinLayers(s)

comparison <- "MN_C9orf72"
comparison_meta_col <- "MN_adjacent"
p_thresh <- 0.001
fc_thresh <- log2(1.5)
condition_col <- "condition"

ident.1 <- "C9orf72"
ident.2 <- "Control"


# keep only the enriched MAP2 spots
s <- subset(s, cells = rownames(s@meta.data[s@meta.data[[comparison_meta_col]] == "MN_adjacent", ]))

# keep only C9orf72 and control 
s <- subset(s, subset = (condition == "C9orf72") | (condition == "Control"))


# check on sample condition 
print(s$condition|>unique())
# should be around 8000
print(dim(s))

Idents(s) <- comparison_meta_col
for(cur_spot_sample in s$sample|>unique()){
  print(cur_spot_sample)
    # p <- SpatialDimPlot(s, images = cur_spot_sample, cells.highlight = list(all_dist_spots, all_adj_spots, all_tdp43_spots, ring_spots), cols.highlight = c("darkblue", "darkred", "yellow", "green", "grey"), ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
    p <- SpatialDimPlot(s, images = cur_spot_sample, ncol = 1, pt.size.factor = 1.2, image.alpha = 0.75)
  print(p)
}


cdr <- colMeans(GetAssayData(s, assay = "Spatial", layer = "counts") > 0)
s@meta.data$cdr <- cdr


# TODO: figure out why this is necessary?
for (name in names(s@assays$SCT@SCTModel.list)) {
  s@assays$SCT@SCTModel.list[[name]]@umi.assay <- 'Spatial'
}
s <- PrepSCTFindMarkers(object = s)

s@meta.data$cdr_centered <- as.numeric((s@meta.data$cdr - mean(s@meta.data$cdr)) / sd(s@meta.data$cdr))
s@meta.data$sample_id <- factor(s@meta.data$sample)

# Get all expression data
expressionmat_full <- GetAssayData(s, assay = "SCT", layer = 'data')
expressionmat_full <- as.matrix(expressionmat_full)



# Get avg_log2FC and percent expression for all genes
Idents(s) <- condition_col
LFC <- FoldChange(object = s, ident.1 = ident.1, ident.2 = ident.2, fc.name = "avg_log2FC", base = 2, assay = "SCT") %>% data.frame()

# Manual min.pct filtering, at least 1 group should be minimum of 10 percent
# and both groups should be at least 1 percent
genes_keep_10pct <- row.names(LFC)[LFC$pct.1 >= 0.1 | LFC$pct.2 >= 0.1]
genes_keep_1pct <- row.names(LFC)[LFC$pct.1 >= 0.01 & LFC$pct.2 >= 0.01]
genes_keep <- intersect(genes_keep_10pct, genes_keep_1pct)

# Remove contamination
if (length(grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)) != 0) {
  genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)]
}

# Filter expression matrix
expressionmat <- expressionmat_full[row.names(expressionmat_full) %in% genes_keep,]

# Cell-level and feature-level meta data for MAST
cdat <- s@meta.data
cdat$wellKey <- row.names(cdat)
fdat <- data.frame(primerid = row.names(expressionmat), row.names = row.names(expressionmat))

# Subset to conditions for comparison
cdat <- cdat[cdat[[condition_col]] %in% c(ident.1, ident.2),]
expressionmat <- expressionmat[,colnames(expressionmat) %in% row.names(cdat)]

# Create MAST object
sca <- FromMatrix(expressionmat, cdat, fdat, check_sanity = FALSE)

# Set reference level for condition
cond <- factor(colData(sca)[[condition_col]])
# TODO: figure out why setting reference as group1, which is not control, in the original script
cond <- relevel(cond, ident.2) # FindMarkers: reference level is "Group1"
colData(sca)[[condition_col]] <- cond


# MAST does not allow ebayes (empirical Bayes estimation to regularize variance) for glmer
# zlm_condition <- zlm(~ condition + sex + age_centered + cdr_centered + gDNA_centered + (1 | sample_id), sca,
#                      ebayes = FALSE, method = "glmer")
print("INFO: fitting model!")
# remove sample random variable due to insufficient variability
zlm_condition <- zlm(~ condition + cdr_centered, sca,
                     ebayes = FALSE, method = "glm", verbose = TRUE)
lrt_name <- paste0(condition_col, ident.1)

print("INFO: performing likelihood ratio test!")
summary_condition <- summary(zlm_condition, doLRT = lrt_name) # FindMarkers: doLRT = "conditionGroup2"

# From FindMarkers code
summary_data <- summary_condition$datatable %>% data.frame()
p_val <- summary_data[summary_data[, "component"] == "H", 4]
genes.return <- summary_data[summary_data[, "component"] == "H", 1]

# Compile results
results <- data.frame(p_val = p_val, gene = genes.return, row.names = genes.return)
results$BH <- p.adjust(results$p_val, method = "BH")

LFC_use <- LFC[match(results$gene, row.names(LFC)),]
results$avg_log2FC <- LFC_use$avg_log2FC

results$DE <- "Not DE"
results$DE[results$avg_log2FC > fc_thresh & results$BH < p_thresh] <- "Upregulated"
results$DE[results$avg_log2FC < -fc_thresh & results$BH < p_thresh] <- "Downregulated"

# For volcano plot labels
results$DE_gene <- NA
results$DE_gene[results$DE != "Not DE"] <- results$gene[results$DE != "Not DE"]

out_file <- glue("{out_data_dir}/{comparison}__{ident.1}_vs._{ident.2}.csv")
write.csv(results, out_file, quote = F)
print(glue("INFO: saved output to {out_file}!"))

output_file <- glue("{out_plot_dir}/{comparison}.pdf")
all_DEs <- dplyr::filter(results, DE != "Not DE" , abs(avg_log2FC) > 1)[["gene"]]

extreme_DEs <- dplyr::filter(results, ((abs(avg_log2FC) > 1) & (BH < 1e-100)))[["gene"]]
# 
genes_neuro_immune_cryptic_splicing_v3 <- c(
  "ABCA1", "AIF1", "B2M", "C1QA", "C1QB", "C1QC", "C1R", "C1S", "C3", "CD14", 
  "CD163", "CD44", "CD74", "CEBPD", "CHI3L1", "CSF1R", "CYFIP1", "FPR1", "GPNMB", 
  "HAMP", "IFI16", "IFI30", "IL1RL1", "KIF5A", "LAPTM5", "NEFL", "NEFM", "NUPR1", 
  "S100A6", "S100A9", "SOD2", "STMN2", "TYROBP", "VIM", "TMEM176B"
)

genes_neuro_immune_cryptic_splicing_v3 <- c(genes_neuro_immune_cryptic_splicing_v3, extreme_DEs)
cur_title <- "MN tracing adjacent DE C9orf72 vs. Control"
pdf(output_file, width = 15, height = 12)
volcano(results, title = str_replace_all(cur_title, "_", " "), p_thresh = 1e-3, fc_thresh = 1, label_genes = genes_neuro_immune_cryptic_splicing_v3)
dev.off()
```













```{r}
volcano <- function(results, title = NULL, label_genes = NULL, p_thresh = 0.05, fc_thresh = 0.585) {
  
  # results <- results %>%
  #   filter(!grepl("AC0", gene_id) & gene_id != "HLA-B")
  
  # Define plot colors
  colors <- c("blue", "red", "black")
  names(colors) <- c("Downregulated", "Upregulated", "Not DE")
  
  # Rename variables 
  results$lfc <- results[["avg_log2FC"]]
  results$padj <- results[["BH"]]
  results$gene <- results[["gene"]]
  
  # Calculate PFC 
  results$neg_logBH <- -log10(results$padj)
  results$neg_logBH[results$neg_logBH == Inf] <- max(results$neg_logBH[results$neg_logBH != Inf]) + 10
  results$PFC <- results$neg_logBH*abs(results$lfc)
  
  # Define DEGs
  results$DE <- "Not DE"
  results$DE[results$padj < p_thresh & results$lfc > fc_thresh] <- "Upregulated"
  results$DE[results$padj < p_thresh & results$lfc < -fc_thresh] <- "Downregulated"
  
  # Gene labeling 
  results$label <- NA

  # If genes not specified, label top 30 by PFC, otherwise label specified genes
  if (is.null(label_genes)) {
    results <- results %>% dplyr::arrange(desc(PFC))
    # all_DE_genes_count <- dplyr::filter(results, DE != "Not DE")|>nrow()
    degs <- results$gene[results$DE != "Not DE"][1:20]
    # degs <- results$gene[results$DE != "Not DE"]
    results$label[results$gene %in% degs] <- results$gene[results$gene %in% degs]
  } else {
    results$label[results$gene %in% label_genes] <- results$gene[results$gene %in% label_genes]
  }
  # 
  # Define basic title if not specified 
  if (is.null(title)) {
    title <- paste0(sum(results$DE != "Not DE"), " DEGs")
  }
  
  # Generate plot 
  plt <- ggplot(data.frame(results), aes(x = lfc, y = neg_logBH, fill = DE, label = label)) + 
    geom_point(aes(size = PFC), alpha = 0.5, shape = 21, stroke = NA) + 
    scale_size_continuous(range = c(3, 12)) + 
    geom_label_repel(color = "black", size = 12, force = 3, min.segment.length = 0, force_pull = 0, box.padding = 1, max.overlaps = Inf,
                     fill = "white", alpha = 0.75, label.size = NA) +
    geom_vline(xintercept=c(-fc_thresh, fc_thresh), linetype = 3) + geom_hline(yintercept= -log10(p_thresh), linetype = 3) +
    scale_fill_manual(values = colors) + 
    theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(color = 'black'), aspect.ratio = 1) + 
    xlim(min(results$lfc[!is.na(results$padj)]) - 0.2, max(results$lfc[!is.na(results$padj)]) + 0.2) +
    # ylim(c(0, 50))+
    ggtitle(paste0(title)) + theme(plot.title = element_text(hjust = 0.5)) + 
    labs(x = "Log2 Fold Change", y = "-log10(Adjusted P-Value)", size = 12) +
    theme(axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14))
  
  return(plt)
}
```

