```{r}
source("../00.ref/config/spatial_config.R")
input_data_dir <- glue("{out_dir_root}/03.seurat_process_final")
library(dplyr)
library(ggpubr)
s <- readRDS(glue("{input_data_dir}/data/seurat_45.2__05.rds"))
output_dir <- glue("{out_dir_root}/05.deconvolution_analysis/02.mg_state_enrichment")
dir.create(output_dir, recursive = T, showWarnings = F)

```


# load module
```{r}
mg_ref <- read.csv("/projects/b1042/Gate_Lab/projects/als-project/spatial/00.ref/mcrioglia_state_ref.csv")|>as_tibble()

ref_list <- mg_ref %>%
  group_by(microgliaState) %>%
  summarise(values = list(gene)) 

named_list <- setNames(ref_list$values, ref_list$microgliaState)


naming_conversion <- c(
  "MG0" = "Homeostatic",
  "MG1" = "Neuronal Surveilance",
  "MG2" = "Inflammatory I",
  "MG3" = "Ribosome Biogenesis",
  "MG4" = "Lipid Processing",
  "MG5" = "Phagocytic",
  "MG6" = "Stress Signature",
  "MG7" = "Glycolytic",
  "MG8" = "Inflammatory II",
  "MG10" = "Inflammatory III", 
  "MG11" = "Antiviral",
  "MG12" = "Cycling"
)


for(cur_mg_module in names(named_list)){
  cur_mg_name <- naming_conversion[[cur_mg_module]]
  cur_mg_genes <- list(named_list[[cur_mg_module]])
  
  cur_col_name <- str_replace_all(cur_mg_name, " ", "_")
  
  s <- AddModuleScore(
    object = s,
    features = cur_mg_genes,
    ctrl = 5,
    assay = "SCT",
    name = cur_col_name
  )
}



```


```{r fig.height=20, fig.width=25}

mt <- s@meta.data|>select(condition, sample)|>unique()
display_order <- c("Control", "C9orf72", "sALS")
mt$condition <- factor(mt$condition, levels = display_order)
sorted_df <- mt[order(mt$condition), ]
images_to_show <- sorted_df$sample






plots  <- SpatialFeaturePlot(s, features = "Inflammatory_II1", images = images_to_show, image.alpha = 0, crop = F, pt.size.factor = 1, combine = FALSE, stroke = NA) 

ratio_adjust <- c(
  "NEUHD481VCL_SCC_19.sl14___V52L06.340___HCBOT" = 0.9,
  "GBB.18.01.A9.sl12___V52L06.298___C3" = 0.75,
  "GBB21.03.A12.sl5___V52L06.340___C12" = 0.8,
  "GBB19.13.A13.sl5___V52L19.016___C9" = 0.8,
  "GWF_19.47_10B_sl13___V52L19.048___HCBOT" = 0.6,
  "GWF_19.47_10B_sl13___V52L19.048___HCTOP" = 0.7,
  "MILLERMI.N14.280.CSC___V52L18.276___D7" = 0.8,
  "MILLERMI.AU.87.sl5___V52L19.037___D12" = 0.85
)

plot_list <- list()

for(cur_plot in plots){
  cur_sample_id <- cur_plot$labels$title
  print(cur_sample_id)
  if(cur_sample_id %in% names(ratio_adjust)){
    plot_list[[cur_sample_id]] <- cur_plot +
          theme(aspect.ratio = ratio_adjust[[cur_sample_id]])
  }else{
    plot_list[[cur_sample_id]] <- cur_plot
  }
  
}


combined_plot <- patchwork::wrap_plots(plot_list, ncol = 5)

# pdf(glue("{out_plot_dir}/{cur_ident}.pdf"), width = 25, height = 20)
print(combined_plot)
# dev.off()


mt_adj <- dplyr::filter(s@meta.data, tdp43_a2_d2 == "TDP43_adjacent")
mt_dist <- dplyr::filter(s@meta.data, tdp43_a2_d2 == "TDP43_distant")

all_cols <- grep("score1$", colnames(mt_adj), value = TRUE)

for(cur_col in all_cols){
  print(cur_col)
  cur_adj <- mt_adj[[cur_col]]
  cur_dist <- mt_dist[[cur_col]]
  
  x_mean <- mean(cur_adj)
  y_mean <- mean(cur_dist)
  cat("Mean of x:", x_mean, "\n")
  cat("Mean of y:", y_mean, "\n")

  
  t <- wilcox.test(cur_adj, cur_dist)
  print(t)
}









mn_adj <- dplyr::filter(s@meta.data, MN_dist_group == "group 1" | MN_dist_group == "group 2")
mn_dist <- dplyr::filter(s@meta.data, MN_dist_group == "group 5")

all_cols <- grep("score1$", colnames(mt_adj), value = TRUE)

for(cur_col in all_cols){
  print(cur_col)
  cur_adj <- mn_adj[[cur_col]]
  cur_dist <- mn_dist[[cur_col]]
  
  x_mean <- mean(cur_adj)
  y_mean <- mean(cur_dist)
  cat("Mean of x:", x_mean, "\n")
  cat("Mean of y:", y_mean, "\n")

  
  t <- wilcox.test(cur_adj, cur_dist)
  print(t)
}






```





