```{r}
source("../00.ref/config/CRISPR_clean_config.R")


seurat_output_dir <- glue("{out_dir_root}/04.seurat")
input_seurat <- glue("{seurat_output_dir}/seurat_04_05.rds")
DEG_out_dir <- glue("{out_dir_root}/05.DEG_717_filter")

s <- readRDS(input_seurat)
```

# add FRS score
```{r}
mt <- read.csv(meta)
```



```{r}
DefaultAssay(s) <- "SCT"
cur_ct <- "CD16 Mono"
s_sub <- subset(s, predicted.celltype.l2 == cur_ct)
# s_sub <- subset(s_sub, subset = diagnosis!="als_c9orf72")
# s_sub <- subset(s_sub, subset = diagnosis!="als_fast")


# Calculate average lognorm expression per donor
meta <- s_sub@meta.data
data <- GetAssayData(s_sub, assay = "SCT", layer = "data")
data <- as.matrix(data)
sum(rownames(meta) != colnames(data))
colnames(data) <- meta$orig.ident
bulk <- t(rowsum(t(data), group = colnames(data)))
for (sample in colnames(bulk)) {
  bulk[,sample] <- bulk[,sample]/sum(colnames(data) == sample)
}




Idents(s_sub) <- "diagnosis_general"

DefaultAssay(s_sub) <- "SCT"
# s_sub <- JoinLayers(s_sub)

# cur_s_LFC <- FoldChange(object = s_sub, ident.1 = "als", ident.2 = "healthy_control", fc.name = "avg_log2FC", base = 2) %>% data.frame()
# 
# genes_keep_10pct <- row.names(cur_s_LFC)[cur_s_LFC$pct.1 >= 0.1 | cur_s_LFC$pct.2 >= 0.1]
# genes_keep_1pct <- row.names(cur_s_LFC)[cur_s_LFC$pct.1 >= 0.01 & cur_s_LFC$pct.2 >= 0.01]
# genes_keep <- intersect(genes_keep_10pct, genes_keep_1pct)

genes_keep <- rownames(s_sub)


res_list <- list()
for(cur_gene in genes_keep){
  cur_data <- as.data.frame(bulk[cur_gene,])
  colnames(cur_data) <- c(cur_gene)
  cur_data[["sample_id"]] <- rownames(cur_data)
  meta_add <- dplyr::select(mt, gex_index, frs_score, diagnosis_general)
  cur_data <- left_join(cur_data, meta_add, by = join_by(sample_id == gex_index))|>
    drop_na()
  cur_res <- cor.test(cur_data[[cur_gene]], cur_data$frs_score)
  cur_pval <- cur_res$p.value
  cur_coor <- cur_res$estimate
  cur_row <- list(
    gene = cur_gene, 
    pval = cur_pval, 
    coor = cur_coor
  )
  res_list[[cur_gene]] <- cur_row
}
res_df <- rbindlist(res_list)|>as.data.frame()

res_df[["p.adj"]] <- p.adjust(res_df$pval, method = "BH")






plot <- ggplot(cur_data, aes(x = frs_score, y = GSTM1)) +
  geom_point() + # Scatter plot
  geom_smooth(method = "lm", col = "blue", se = FALSE) + # Add regression line
  theme_minimal() +
  labs(
    title = "Correlation between Column1 and Column2",
    x = "frs_score",
    y = "GSTM1 SCT expr"
  ) +
  # Add annotation for correlation coefficient and p-value
  annotate(
    "text",
    x = max(cur_data$frs_score) * 0.7, y = max(cur_data$GSTM1),
    label = paste0(
      "r = ", round(cur_coor, 2),
      "\np = ", signif(cur_pval, 3)
    ),
    hjust = 0, vjust = 1, size = 5, color = "red"
  )

# Print the plot
print(plot)
```

