####################################################################
# Charles Zhang
# Gate Lab
# Northwestern University
# 09/27/2023
####################################################################
# Perform differential expression on all level 2 predicted cell tyeps
####################################################################
# See README.md for additional links
options(echo = TRUE)

source("../../00.ref/config/CRISPR_clean_config.R")
seurat_output_dir <- glue("{out_dir_root}/04.seurat")
input_seurat <- glue("{seurat_output_dir}/seurat_04_05.rds")
DEG_out_dir <- glue("{out_dir_root}/05.DEG_718_adaptive_only")
dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE )

method <- "SCT"
BH_thres <- 0.01
lfc_thres <- 0.585
cluster_col <- "predicted.celltype.l2"
condition_col <- "diagnosis"
skip_cov <- FALSE
overwrite <- TRUE

degs_path<-glue("{DEG_out_dir}/degs/{condition_col}/{method}")
plots_path<-glue("{DEG_out_dir}/plots/{condition_col}/{method}")

dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(degs_path, showWarnings = FALSE, recursive = TRUE)
dir.create(plots_path, showWarnings = FALSE, recursive = TRUE)

s<-readRDS(input_seurat)
DefaultAssay(s) <- "RNA"

# remove cells without valid cell type annotation, this is relevant when labels are generated by matching barcodes
# with a reference seurat object
cells.use<-s@meta.data[which(is.na(s@meta.data[[cluster_col]])==F),]|>rownames()
s<- subset(s, cells = cells.use)
s<-subset(s, subset = diagnosis!="als_c9orf72")

# generate all comparison permutations
clusters <- s@meta.data[[cluster_col]] |> unique() |> sort()
sample_conditions <- s@meta.data[[condition_col]] |> unique() |> sort()

comparisons <- combinations(n = length(sample_conditions), r = 2, v = sample_conditions)
comparisons <- split(comparisons, seq(nrow(comparisons)))

# add diagnnosis_celltype to metadata for identity matching during DEG analysis
s@meta.data$diagnosis_cluster <- glue('{s@meta.data[[cluster_col]]} - {s@meta.data[[condition_col]]}')
Idents(s) <- 'diagnosis_cluster'


# get latent vars
# all_latent_vars <- colnames(s@meta.data)
# latent_vars_to_use <- all_latent_vars[grep(all_latent_vars, pattern="sex|age", ignore.case = T)]
#
# # create dir for each of the latent var
# all_cov<-c(latent_vars_to_use, paste0(latent_vars_to_use, collapse="_"), "no_cov")
# if(skip_cov){
#   all_cov<-c("no_cov")
# }
# just use age and sex as covariates to save run time
all_cov <- c("age_sex")

print("INFO: Covariates to test for:")
print(all_cov)
for (cur_cov in all_cov){
  dir.create(glue("{degs_path}/{cur_cov}"), showWarnings = TRUE)
  dir.create(glue("{plots_path}/{cur_cov}"), showWarnings = TRUE)
}


for(cluster in clusters) {
  if(cluster == "Doublet"){
    next
  }
  for(comparison in comparisons) {
    title <- glue("{cluster}: {comparison[1]} vs. {comparison[2]}")|> str_replace_all("_", " ")
    print(title)
    filename  <-  gsub(" ", "_", glue("{cluster}__{comparison[1]}_vs._{comparison[2]}"))
    cur_s <- subset(s, diagnosis_cluster==glue("{cluster} - {comparison[1]}") | diagnosis_cluster==glue("{cluster} - {comparison[2]}"))
    print(unique(cur_s$diagnosis_cluster))

    # each sample must have two cells to correctly calculate LFC
    if(all(cur_s@meta.data$sample_id|>table()>1) != TRUE){
      print(glue("Skipped {title}"))
      next
    }

    Idents(cur_s) <- condition_col
    t_cell_receptors <- grep("^TR", rownames(cur_s), value = TRUE)
    b_cell_receptors <- grep("^IG", rownames(cur_s), value = TRUE)
    genes_keep <- c(t_cell_receptors, b_cell_receptors)

    # if (length(grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)) != 0) {
    #   genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)]
    # }

    # Put MT genes back
    if (length(grep(pattern = "^RPS|^RPL|^HB", x = genes_keep)) != 0) {
      genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^HB", x = genes_keep)]
    }

    # remove non expressed genes
    t <- FoldChange(object = s, ident.1 = glue("{cluster} - {comparison[1]}"), ident.2 = glue("{cluster} - {comparison[2]}"), fc.name = "avg_log2FC", base = 2) %>% data.frame()
    t2 <- t[genes_keep,]
    genes_keep <- row.names(t2)[t2$pct.1 >= 0.01 & t2$pct.2 >= 0.01]


    for(cur_cov_str in all_cov){
      cur_cov <-strsplit(cur_cov_str, "_")[[1]]
      print("cov:")
      print(cur_cov)
      if(cur_cov_str == "no_cov"){
        cur_cov <- NULL
      }
      cur_deg_out_file <- glue("{degs_path}/{cur_cov_str}/{condition_col}___{filename}.csv")
      if(file.exists(cur_deg_out_file)) {
        next
      }else{
        degs <- find_degs(s,
                          genes_to_test = genes_keep,
                          save_path = cur_deg_out_file,
                          group_1 = glue("{cluster} - {comparison[1]}"),
                          group_2 = glue("{cluster} - {comparison[2]}"),
                          logfc.threshold = -Inf,
                          latent.vars = cur_cov,
                          mode = method)
      }
    }
  }
}

# combine all pdfs
# for (cur_cov in all_cov){
#   cur_plot_dir <- glue("{plots_path}/{cur_cov}")
#   all_pdfs<-list.files(cur_plot_dir, full.names = T, pattern = "[^!]")
#   qpdf::pdf_combine(all_pdfs, output=glue("{plots_path}/{cur_cov}/!combined_{condition_col}.pdf"))
# }
