####################################################################
# Charles Zhang
# Gate Lab
# Northwestern University
# 09/27/2023
####################################################################
# Perform differential expression on all level 2 predicted cell tyeps
####################################################################
# See README.md for additional links
options(echo = TRUE)

source("../../00.ref/config/immune_panel_config.R")
seurat_output_dir <- glue("{out_dir_root}/04.seurat")
input_seurat <- glue("{seurat_output_dir}/seurat_SCT_mapped_04_02.rds")
DEG_out_dir <- glue("{out_dir_root}/05.DEG_1105_immune_enriched")
dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE )

method <- "SCT"
BH_thres <- 0.01
lfc_thres <- 0.585
cluster_col <- "predicted.celltype.l2"
condition_col <- "diagnosis"
skip_cov <- TRUE # since only female is present, can't use this
overwrite <- TRUE
print(glue("Overwrite toggile is {overwrite}"))


degs_path<-glue("{DEG_out_dir}/degs/sALS_hc/{method}")
plots_path<-glue("{DEG_out_dir}/plots/sALS_hc/{method}")

dir.create(DEG_out_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(degs_path, showWarnings = FALSE, recursive = TRUE)
dir.create(plots_path, showWarnings = FALSE, recursive = TRUE)

s<-readRDS(input_seurat)
DefaultAssay(s) <- "RNA"


# remove cells without valid cell type annotation, this is relevant when labels are generated by matching barcodes
# with a reference seurat object
cells.use<-s@meta.data[which(is.na(s@meta.data[[cluster_col]])==F),]|>rownames()
s <- subset(s, cells = cells.use)
s <- subset(s, subset = diagnosis!="als_c9orf72")
print(s@meta.data$diagnosis|>unique())


# generate all comparison permutations
clusters <- s@meta.data[[cluster_col]] |> unique() |> sort()
sample_conditions <- s@meta.data[[condition_col]] |> unique() |> sort()

comparisons <- combinations(n = length(sample_conditions), r = 2, v = sample_conditions)
comparisons <- split(comparisons, seq(nrow(comparisons)))

# add diagnnosis_celltype to metadata for identity matching during DEG analysis
s@meta.data$diagnosis_cluster <- glue('{s@meta.data[[cluster_col]]} - {s@meta.data[[condition_col]]}')
Idents(s) <- 'diagnosis_cluster'
s <- JoinLayers(s)

# covariates
all_cov <- c("age_sex")

print("INFO: Covariates to test for:")
print(all_cov)
for (cur_cov in all_cov){
  dir.create(glue("{degs_path}/{cur_cov}"), showWarnings = TRUE)
  dir.create(glue("{plots_path}/{cur_cov}"), showWarnings = TRUE)
}


for(cluster in clusters) {
  if(cluster == "Doublet"){
    next
  }
  for(comparison in comparisons) {
    title <- glue("{cluster}: {comparison[1]} vs. {comparison[2]}")|> str_replace_all("_", " ")
    filename  <-  gsub(" ", "_", glue("{cluster}__{comparison[1]}_vs._{comparison[2]}"))
    cur_s <- subset(s, diagnosis_cluster==glue("{cluster} - {comparison[1]}") | diagnosis_cluster==glue("{cluster} - {comparison[2]}"))
    print(unique(cur_s$diagnosis_cluster))


    # each sample must have two cells to correctly calculate LFC
    if(all(cur_s@meta.data$sample_id|>table()>2) != TRUE){
      print(glue("Removing samples for file: {title}"))
    }
    t <- cur_s@meta.data$sample_id|>table()
    samples_keep <- names(t[t>2])
    if(length(samples_keep) < 4){
      print("Skip due to inadequate cells in samples")
      next
    }
    cur_s <- subset(cur_s, sample_id %in% samples_keep)


    # check if both comparison groups have at least 3 cells
    ncell_1 <- nrow(dplyr::filter(cur_s@meta.data, diagnosis_cluster==glue("{cluster} - {comparison[1]}")))
    ncell_2 <- nrow(dplyr::filter(cur_s@meta.data, diagnosis_cluster==glue("{cluster} - {comparison[2]}")))
    if(ncell_1 < 3 | ncell_2 < 3){
      print("Skip due to inadequate cells in one group.")
      next
    }


    Idents(cur_s) <- condition_col
    cur_s <- JoinLayers(cur_s)
    cur_s_LFC <- FoldChange(object = cur_s, ident.1 = comparison[1], ident.2 = comparison[2], fc.name = "avg_log2FC", base = 2) %>% data.frame()

    genes_keep_10pct <- row.names(cur_s_LFC)[cur_s_LFC$pct.1 >= 0.1 | cur_s_LFC$pct.2 >= 0.1]
    genes_keep_1pct <- row.names(cur_s_LFC)[cur_s_LFC$pct.1 >= 0.01 & cur_s_LFC$pct.2 >= 0.01]
    genes_keep <- intersect(genes_keep_10pct, genes_keep_1pct)

    # if (length(grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)) != 0) {
    #   genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^MT-|^HB", x = genes_keep)]
    # }

    # Put MT genes back
    if (length(grep(pattern = "^RPS|^RPL|^HB", x = genes_keep)) != 0) {
      genes_keep <- genes_keep[-grep(pattern = "^RPS|^RPL|^HB", x = genes_keep)]
    }

    # remove genes not present in SCT assay
    all_elements_present <- all(genes_keep %in% rownames(cur_s@assays$SCT))
    if (!all_elements_present & method == "SCT") {
      # Elements in vector1 but not in vector2
      not_in_SCT <- genes_keep[!genes_keep %in% rownames(cur_s@assays$SCT)]
      cat("Elements in not present in SCT:", not_in_SCT, "\n")
      genes_keep <- genes_keep[!genes_keep %in% not_in_SCT]
    }

    for(cur_cov_str in all_cov){
      cur_cov <-strsplit(cur_cov_str, "_")[[1]]
      print("cov:")
      print(cur_cov)
      if(cur_cov_str == "no_cov"){
        cur_cov <- NULL
      }
      cur_deg_out_file <- glue("{degs_path}/{cur_cov_str}/{condition_col}___{filename}.csv")
      if(file.exists(cur_deg_out_file) & overwrite == FALSE) {
        print(glue("{cur_deg_out_file} exists! Skipped!"))
        next
      }else{
        degs <- find_degs(s,
                          genes_to_test = genes_keep,
                          save_path = cur_deg_out_file,
                          group_1 = glue("{cluster} - {comparison[1]}"),
                          group_2 = glue("{cluster} - {comparison[2]}"),
                          logfc.threshold = -Inf,
                          latent.vars = cur_cov,
                          mode = method)
      }
    }
  }
}

# combine all pdfs
# for (cur_cov in all_cov){
#   cur_plot_dir <- glue("{plots_path}/{cur_cov}")
#   all_pdfs<-list.files(cur_plot_dir, full.names = T, pattern = "[^!]")
#   qpdf::pdf_combine(all_pdfs, output=glue("{plots_path}/{cur_cov}/!combined_female_c9_hc.pdf"))
# }
